### PR TITLE
Fix #1297

### LINKED ISSUE #1297: PicklePersistence of user_data set within conversations
### Steps to reproduce
1. In [persistentconversationbot.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/378784f55e0c00c5b85659cdc7edb278557bdc0b/examples/persistentconversationbot.py#L150), change `persistent=True` to `persistent=False`
2. Start the bot, give the bot some information to store

3. Stop bot
4. Start bot again, send command `/show_data`. It will be empty

### Expected behaviour
`user_data` changed within a conversation should be persisted even if the conversation is not
(i.e., I would expect this)

### Actual behaviour
`user_data` changed within a conversation that is not persisted, will not be persisted

### Configuration
Raspbian GNU/Linux 9 (stretch)

**Version of Python, python-telegram-bot & dependencies:**

```
python-telegram-bot 11.1.0
certifi 2018.01.18
future 0.17.1
Python 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
```

### Research so far:

1.  When the conversation is persisted, the `user_data` will only be persisted, if `single_file = True`. This is because this will trigger `dump_singlefile()` in [picklepersistence.py](https://github.com/python-telegram-bot/python-telegram-bot/blob/378784f55e0c00c5b85659cdc7edb278557bdc0b/telegram/ext/picklepersistence.py#L97) on update in Conversation. When setting `single_file = False`, `user_data` will not be persisted
2. Things go south in [`update_user_data()`](https://github.com/python-telegram-bot/python-telegram-bot/blob/378784f55e0c00c5b85659cdc7edb278557bdc0b/telegram/ext/picklepersistence.py#L195). Printing the result of

    ```
    self.user_data.get(user_id) == data:
    ```
    always gives `True` even though `self.user_data.[user_id]` _has_ changed after user input (as one can test by printing it).

I therefore conclude, that `self.user_data[user_id]` must be changed somewhere along the way _before_ `update_user_data()` is called. Still, I can't pinpoint, where that happens. Will try and find it.

If you have a clue, please let me know :)

### PR DESCRIPTION
**Pull request by Eldinnie**
This makes a deepcopy of the user_data and chat_data dict as suggested by @Bibo-Joshi
Fixes #1297

### CODE REVIEW

**Comment by jsmnbom** [comment]
@Eldinnie So we are fine with the performance penalty "issue" as raised by @Bibo-Joshi in #1301 then?

**Comment by jsmnbom** [comment]
I'm personally fine with it. If people were gonna store massive amounts of data, they would use a proper library/database for it instead I think.

**Comment by Eldinnie** [comment]
I think we have no choice, and I think the performance penalty will be minimal. Also the fix proposed in #1301 (oops, missed that one before stating on this) means it;s a choice between `deepcopy()` and unneeded writes to disk (which are even more time consuming) so I guess just deepcopying is fine

**Comment by jsmnbom** [comment]
CI fail unrelated, will fix on master.

**Pull request merged**
