### PR TITLE
Comply with PEP561

### LINKED ISSUE #2166: mypy doesn't pick up type hints[BUG]
### Steps to reproduce
1. import python-telegram-bot modules into your `test.py` file (e.g. `from telegram import InlineKeyboardMarkup`)

2. run `mypy test.py`

3. receive the following output `error: Skipping analyzing 'telegram': found module but no type hints or library stubs`

### Expected behaviour
mypy should pickup the typehints as they've been added in the latest release (version `13` )

### Actual behaviour
mypy doesn't pickup the typehints.

I'm confident this can be solved by either

1. adding `python-telegram-bot` to `typeshed` 
2. adding a `py.typed` file

More information can be found [here.](https://stackoverflow.com/questions/60856237/mypy-cant-find-type-hints-for-black)

### Configuration
**Operating System:**
Ubuntu 18.04

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 13.0
certifi 2020.06.20
Python 3.8.0 (default, Oct 30 2020, 19:06:04)  [GCC 7.5.0]
### Logs
```
error: Skipping analyzing 'telegram.ext': found module but no type hints or library stubs
note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
error: Skipping analyzing 'telegram': found module but no type hints or library stubs
error: Skipping analyzing 'telegram.ext': found module but no type hints or library stubs
error: Skipping analyzing 'telegram': found module but no type hints or library stubs
```

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
should close #2166

### CODE REVIEW

**Comment by letmejustputthishere** [comment]
I removed the `telegram/py.typed` and uninstalled the previous `python-telegram-bot` package. After installing the `pep561` branch the same error occurs again. This doesn't solve the problem for me.

I don't know if it's worth mentioning: I'm using poetry as a package manager.

**Comment by Bibo-Joshi** [comment]
Okay … I'll look into it :)

**Comment by Bibo-Joshi** [comment]
`py.typed` was just in the wrong dir. I've checked that `python setup.py sdist bdist_wheel` includes `telegram/py.typed` both in the wheel and in the `.tar.gz` and installing from this branch also worked. @letmejustputthishere could you double check on your end by installing from this branch?

**Comment by letmejustputthishere** [comment]
It works like a charm, thanks a lot!

**Pull request merged**
