### PR TITLE
Drop `telegram(.ext).` prefixes

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
As suggested in https://t.me/c/1494805131/32127. Build will be up soonish on rtd.

URLs seem to be unchanged.

Before a merge, I want to test if this would imply any changes for rulesbot.

### CODE REVIEW

**Comment by Poolitzer** [comment]
@Bibo-Joshi And we should check search

**Comment by Bibo-Joshi** [comment]
Both search and rulesbot-search (which are basically the same thing, IG) seem to work fine :)

**Review by harshil21 — COMMENTED** [review]
Do we want to drop the prefixes even for the modules?

**Comment by Bibo-Joshi** [comment]
> Do we want to drop the prefixes even for the modules?

For `telegram.{error, request, constants, …}` I kept them so that it's clear at first glance how to import them. Is that what you mean?

**Comment by harshil21** [comment]
@Bibo-Joshi yes

**Review by Poolitzer — APPROVED** [review]
Yes, thank you, looks perfect.

**Review by harshil21 — APPROVED** [review]

**Pull request merged**
