### PR TITLE
Rename shortcut functions to snake_case

### PR DESCRIPTION
**Pull request by saschalalala**
I renamed some functions in message.py to snake case for consistency. Are there any other files that need function renaming?

### CODE REVIEW

**Comment by bomjacob** [comment]
I know there are a few other places... maybe if you search for "*args, **kwargs" or something you'll find them.. 
Also you can add yourself to AUTHORS.rst if you want :)

**Comment by saschalalala** [comment]
Found some more, working on it.

**Comment by saschalalala** [comment]
Ok. There is more. Give me one or two days to look through the code, there are some files, I did not look at yet.

**Comment by saschalalala** [comment]
Ok, I'm done. I read through all the code and will go to bed now. That should really have been it now.

**Comment by jh0ker** [comment]
@saschalalala Good night :)

**Comment by saschalalala** [comment]
Okay, some tests fail because the MockBot also has to be reworked a little. However, I reread the contributing doc and set up my environment to run the tests locally before pushing the changes and I receive some other errors like `ModuleNotFoundError: No module named 'telegram.vendor.ptb_urllib3.urllib3'` Anything I can do about that?

**Comment by Eldinnie** [comment]
@saschalalala make sure to read the installation instructions carefully. You did not pull the submodule. Easiest way to fix is running `git submodule update --init --recursive`

**Comment by saschalalala** [comment]
Okay, thanks. I overlooked that because I only read the contributing guide m(

The tests are running fine on my machine now.

**Comment by Eldinnie** [comment]
@saschalalala thanks for pointing that out, we need to add this change in our contributing guide aswell.

**Comment by saschalalala** [comment]
Is there anything I can do regarding the two failed tests or are they related to the test environment and network issues?

**Comment by Eldinnie** [comment]
```
Flake8...................................................................Failed
hookid: flake8
telegram/precheckoutquery.py:98:100: E501 line too long (101 > 99 characters)
```
this needs to be fixed, the timed out error is nothing to worry about.

**Comment by jh0ker** [comment]
This looks great, thank you for the effort!

**Pull request merged**
