### PR TITLE
Fix "key not found" exception if the very first message handler in a …

### PR DESCRIPTION
**Pull request by LiaungYip**
…ConversationHandler returns the state ConversationHandler.END.

### CODE REVIEW

**Comment by jh0ker** [comment]
Thank you for your contribution! Did you already add yourself to AUTHORS.rst?

**Comment by LiaungYip** [comment]
@jh0ker I have added myself to AUTHORS.rst.

**Comment by jh0ker** [comment]
Ah, yapf is failing. Probably because you could change this
```python
if new_state == self.END: 
    if key in self.conversations:
        del self.conversations[key]
```
to this
```python
if new_state == self.END and key in self.conversations:
    del self.conversations[key]
```

**Comment by LiaungYip** [comment]
Ah, I hadn't expected to fall afoul of the build system for a single line change.

I'll fix that formatting so it's as `yapf` expects and see if the build passes... if build still fails, I'll actually follow the process in CONTRIBUTING.rst.

**Comment by jh0ker** [comment]
Could you include a fix for https://github.com/python-telegram-bot/python-telegram-bot/issues/373#issuecomment-238839786 too, if it's not too much work?

**Comment by jh0ker** [comment]
friendly ping @LiaungYip

**Comment by jh0ker** [comment]
Thank you for your contribution @LiaungYip :)

I included a fix for the comment I linked earlier and added unit tests for these two cases. By the way, your take on the `if` turned out to be correct, I only added an explicit `else` clause:

```python
if new_state == self.END:
    if key in self.conversations:
        del self.conversations[key]
    else:
        pass
```

**Pull request merged**
