### PR TITLE
Support v3.6 API

### PR DESCRIPTION
**Pull request by code1mountain**
Added support for connected_website from Bot API v3.6.

Update: Also added support for parse_modes in captions. I added only tests for parse_mode in captions in tests/test_photo.py, because adding a test for all kind of messages that contain a caption is redundant.

Update 2: I added the support for the parse_mode parameter in all InlineQueryResults

Update 3: Added the support streaming parameter to telegram.Bot.send_video and InputMediaVideo. The streaming parameter will not work for any videos you send by file_id, that don't support streaming already or sending by file or url for files, the telegram server already downloaded once. Anyways, Telegram won't raise an Error for that.

Fixes part 1 + 3 + 4 from issue #1005

### CODE REVIEW

**Comment by Eldinnie** [comment]
For Now I renamed the PR, since it already contains two of the newly added features. Will look in depth later.

**Comment by jeffffc** [comment]
I think the `InlineQueryResult*` objects contains new `parse_mode` field too

**Comment by code1mountain** [comment]
Yeah, I just saw that parse_mode also affects `InlineQueryResult*`. I will add it asap

**Comment by Eldinnie** [comment]
Ok, I finished up and made some adjustments.
Let's see what CI thinks

**Comment by Eldinnie** [comment]
Ok, diff coverage is up too 100%.
Review please, @tsnoam @jh0ker @bomjacob ?

**Comment by tsnoam** [comment]
Also needs to be fixed on `send_voice`

**Comment by tsnoam** [comment]
@code1mountain 
I've created the needed changes but i can't seem to push into your repo. Have you enabled edits by maintainers?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Eldinnie** [comment]
@tsnoam Yes, because I did too

**Comment by tsnoam** [comment]
my bad, i tried to push to the wrong branch. 
now it's pushed, i'm waiting for travis and if it goes well i'll squash-merge.

**Comment by tsnoam** [comment]
@code1mountain thanks for your contribution!

**Pull request merged**
