### PR TITLE
echobot: simpler exception handling

### PR DESCRIPTION
**Pull request by rahiel**
Catch the HTTPException and URLError through the library. Catching of URLError depends on https://github.com/python-telegram-bot/python-telegram-bot/pull/161.

Not ready to be merged yet, I'll clean it up later.

### CODE REVIEW

**Comment by jh0ker** [comment]
#161 has been merged :) There are new exceptions that subclass `TelegramError` and are more descriptive, please check them out!

**Comment by rahiel** [comment]
It looks much better now, thanks @tsnoam :smile:

**Comment by tsnoam** [comment]
@rahiel do u want to make changes to your PR?

**Comment by tsnoam** [comment]
@rahiel and it's my pleasure 😊

**Comment by rahiel** [comment]
> @rahiel do u want to make changes to your PR?

Do you have any suggestions?

**Comment by tsnoam** [comment]
@rahiel sorry, i missed your new commits. will read them and get back to you

**Pull request merged**
