### PR TITLE
Download changed

### PR DESCRIPTION
**Pull request by OctoNezd**
Now accepts arg `out`, which accepts a file-like object

### CODE REVIEW

**Comment by OctoNezd** [comment]
For some reason, all checks fail on send_contact. Btw, it doesnt get affceted by my changes.

**Comment by OctoNezd** [comment]
Tests on mine seerver says everything(except Botan) is fine

**Comment by lisitsky** [comment]
Travis [says](https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/173654104#L723), it got HTTP Error 429 "Too many requests" from Telegram API during tests:

```
======================================================================
ERROR: test_send_contact (tests.test_bot.BotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/tests/base.py", line 84, in newfunc
    rc = func(*args, **kwargs)
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/tests/test_bot.py", line 353, in test_send_contact
    message = self._bot.send_contact(self._chat_id, phone, name, last)
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/telegram/bot.py", line 124, in decorator
    result = func(self, *args, **kwargs)
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/telegram/bot.py", line 150, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/telegram/utils/request.py", line 205, in post
    **urlopen_kwargs)
  File "/home/travis/build/python-telegram-bot/python-telegram-bot/telegram/utils/request.py", line 156, in _request_wrapper
    raise NetworkError('{0} ({1})'.format(message, resp.status))
telegram.error.NetworkError: Too Many Requests: retry after 24518 (429)
```

I think it will be very hard to test, because such errors could emerge everywhere during repeating tests.

**Comment by jh0ker** [comment]
OK I fixed the pre-commit hooks, so I'll merge

**Comment by OctoNezd** [comment]
yay

**Pull request merged**
