### PR TITLE
Minor readability improvement and test for valid Bot token

### PR DESCRIPTION
**Pull request by artemrys**
Improvements:

 * use a wildcard instead of naming an unused variable
 * add test for valid Bot token

### CODE REVIEW

**Comment by artemrys** [comment]
Py3.5 fails on `test_delete_chat_photo`. Unrelated to the change.

**Comment by artemrys** [comment]
As far as I researched the code - it is connected with flakiness.
Decorator `pytest.flaky` is trying to solve this issue.
But something it is not enough retries to test pass.

**Comment by Bibo-Joshi** [comment]
Hey. After some internal discussion, we decided against this PR. I.e. valid bot tokens are already tested implicity by actually running the test suite and the wildcard thingy, while valid, maybe doesn't need it's own PR. Thank you for taking the time, nonetheless!

**Comment by artemrys** [comment]
No problems :)

**Pull request closed without merging**
