### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by david-shiko**
### Checklist for PRs

- [ ] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [ ] Created new or adapted existing unit tests
- [ ] Added myself alphabetically to `AUTHORS.rst` (optional)
- [ ] Added new classes & modules to the docs

### If the PR contains API changes (otherwise, you can delete this passage)

* New classes:
    - [ ] Added `self._id_attrs` and corresponding documentation
    - [ ] `__init__` accepts `**_kwargs`
    
* Added new shortcuts:
    - [ ] In `Chat` & `User` for all methods that accept `chat/user_id`
    - [ ] In `Message` for all methods that accept `chat_id` and `message_id`
    - [ ] For new `Message` shortcuts: Added `quote` argument if methods accepts `reply_to_message_id`
    - [ ] In `CallbackQuery` for all methods that accept either `chat_id` and `message_id` or `inline_message_id`
    
* If relevant:

    - [ ] Added new constants at `telegram.constants` and shortcuts to them as class variables
    - [ ] Added new handlers for new update types
    - [ ] Added new filters for new message (sub)types
    - [ ] Added or updated documentation for the changed class(es) and/or method(s)
    - [ ] Updated the Bot API version number in all places: `README.rst` and `README_RAW.rst` (including the badge), as well as `telegram.constants.BOT_API_VERSION`
    - [ ] Added logic for arbitrary callback data in `tg.ext.Bot` for new methods that either accept a `reply_markup` in some form or have a return type that is/contains `telegram.Message`

### CODE REVIEW

**Comment by Bibo-Joshi** [comment]
Uhm, what's the goal of this PR? IISC it only contains commits from an old version of the doc-fixes branch, but no new changes at all ...

**Comment by padi1234** [comment]
> Hey there. Relax, I am just a little warning for the maintainers to release directly after merging your PR, otherwise we have broken examples and people might get confused :)

**Review by padi1234 — APPROVED** [review]

**Comment by david-shiko** [comment]
> Uhm, what's the goal of this PR? IISC it only contains commits from an old version of the doc-fixes branch, but no new changes at all ...

Sorry, I pretty new in PR. I wanted to add to this page https://python-telegram-bot.readthedocs.io/en/stable/telegram.utils.request.html
Default val to cop_pol_size.

**Comment by Bibo-Joshi** [comment]
Ah, I see. TBH I don't think it's worth the effort since that class will be completely rewritten for asyncio

**Pull request closed without merging**
