### PR TITLE
Fix wrong signature call for ConversationHandler.TIMEOUT handlers (issue #1652)

### PR DESCRIPTION
**Pull request by tobiaswicker**
Fix for issue #1652

### CODE REVIEW

**Comment by tobiaswicker** [comment]
Forced push was necessary to trigger the checks to run again, because one failed for unrelated reasons.

**Comment by Eldinnie** [comment]
`Thanks for making this fix.
Can we explore adding a test to make sure this (keeps) work(ing/s) as intended?

**Comment by tobiaswicker** [comment]
@Eldinnie PTB does have tests for the `ConversationHandler` and there is even a `test_conversation_handler_timeout_state()` test case that specifically tests the `ConversationHandler.TIMEOUT` state. I think the issue you are talking about, is that those tests don't `use_context`, right?

So would you like to see the existing tests migrated to use context or rather have separate tests? I'd opt for the latter for backward compatibility for now.

**Comment by Poolitzer** [comment]
@tobiaswicker Switching all the tests to contexts is actually an issue, #1509

**Comment by tobiaswicker** [comment]
@Poolitzer OK, thanks! 

@Eldinnie does the mentioned issue satisfy your request for a test or have you had a test in mind that wouldn't be covered by migrating any of the existing tests?

**Comment by Poolitzer** [comment]
@tobiaswicker I am very sure that solving that issue will satisfy his testing needs

**Comment by Bibo-Joshi** [comment]
@Poolitzer Note, that #1509 is currently assigned only to the v13,0 milestone, which will probably not be closed too soon.

**Comment by Poolitzer** [comment]
@Bibo-Joshi I mean, we are talking about a test for a callback here. I dont think it will break soon enough that we will have a problem with adding this test later, do you?

**Comment by Bibo-Joshi** [comment]
@Poolitzer I guess not. Just wanted to mention it ;)

**Comment by Poolitzer** [comment]
@Bibo-Joshi Fair enough

**Comment by Eldinnie** [comment]
@tobiaswicker IMO the new PR should be paired with a test. One that would fail without this fix, and will pass with this fix.

**Comment by tsnoam** [comment]
@tobiaswicker thankyou for your contribution

**Pull request merged**
