### PR TITLE
Remove sleep from jobqueue tests. Solves #957

### LINKED ISSUE #957: In test_jobqueue.py (maybe others), wait longer (but explicitly) for expected jobs to run
Hi, during my last review the [CI reported an error](https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/322945105) in tests/test_jobqueue.py TestJobQueue test_error after scheduling a job to run after 20 ms and, after waiting 30 ms, seeing it hadn't run. One possibility is that the environment the tests are run in can't reliably resume execution in under 30 ms, and the two threads just ran out of order. If that's the case, would you guys be interested in changing some/all of those tests from:

```python
      def test_run_once(self, job_queue):
          job_queue.run_once(self.job_run_once, 0.01)
-         sleep(0.02)
          assert self.result == 1
```

to something like:

```python
      def test_run_once(self, job_queue):
          job_queue.run_once(self.job_run_once, 0.01)
+         assert self.job_ran.wait(10)
          assert self.result == 1
```

with:

```python
  class TestJobQueue(object):
      result = 0
      job_time = 0
+     job_ran = threading.Event()

      @pytest.fixture(autouse=True)
      def reset(self):
          self.result = 0
          self.job_time = 0
+         self.job_ran.clear()

      def job_run_once(self, bot, job):
          self.result += 1
+         self.job_ran.set()
```

which would cause the tests to wait explicitly until the job executes, but give up (and signal failure) after 10 seconds instead of just 10 ms?

### PR DESCRIPTION
**Pull request by Ambro17**
I added freezegun depdendency to requirements-dev to avoid the need of sleeping to test the jobqueue. This will hopefully help to make tests more deterministics, as sleeps are a bit treasonous with precise timings.

My approach was creating a frozen job queue fixture that yields the job queue itself and the frozen time to be manually advanced.
I also added a friendly-named helper function to 'time travel' and execute jobs due in the future, by manuallly ticking the frozen time and explicitly run due jobs calling job_queue.tick()

Any suggestions are welcome

P.S: If you feel like adding a dependency for this is overkill please read #957. Both `threading.Event` and semaphores were evaluated and discarded because either they fail to cover some cases (threading.Event ca)or they make too complex-to-read code (Semaphores).

Closes #957

### CODE REVIEW

**Comment by Eldinnie** [comment]
Hi,

Thanks for you contribution. As you can see, tests fail because pre-commit is not happy. Did you install your environment as suggested in our [contribution guide](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst)?. Can you fix the pre-commit errors so travis is happy? I will make a more in depth review afterwards.

Pieter

**Comment by jsmnbom** [comment]
Turns out the issue wasn't necessarily with your code, but rather a config issue. Please merge from master, so we can actually see if pylint is satisfied :)

**Comment by Eldinnie** [comment]
Whoops, thanks for finding that @jsmnbom

**Comment by Ambro17** [comment]
Hi, i merged master and made some code-style fixes to improve pylint score. I did follow contributing guidelines but pylint is skipped while commiting. I inspected `.pre-commit-config` and it seems it only cares about files under `telegram` directory. 
```yaml
    hooks:
    -   id: pylint
        files: ^telegram/.*\.py$
```  
Maybe we should modify files regex to include files under `tests`?

**Comment by jsmnbom** [comment]
Now that's kinda curious that the CI would then get mad at you, we'll look into it at some point.

It looks like there's some problem on py2? https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/500894791#L2188
Failures on other versions are unrelated afaik, but these seem related. Anything you can reproduce->fix ?

**Comment by Ambro17** [comment]
Yeah, i'll see it when i have time. It's strange because it didn't happen locally on any of the times i ran it so it must be some weird config. I'll comment here any update

**Comment by plammens** [comment]
Any updates on this? I'd be happy to help if I can. I feel like the need for deterministic tests is intensifying every time more tests for `JobQueue` and other time-related stuff are added, or the existing ones are extended.

**Comment by Ambro17** [comment]
I'm not working on this anymore. it seems a problem of Travis rather than the code now so it should be easier to fix

**Comment by Bibo-Joshi** [comment]
> I'm not working on this anymore. it seems a problem of Travis rather than the code now so it should be easier to fix

Hey. We switched to GitHub Actions by now and personally I haven't experienced any issues with `test_jobqueue`.

@Ambro17 I didn't really dive into the discussion of this pr and #957. Do you think we can close this or is there something we still need to change?

**Comment by Ambro17** [comment]
This issue can be closed

**Pull request closed without merging**
