### PR TITLE
Add kwargs to data dict

### LINKED ISSUE #733: Make sure Bot methods properly use kwargs for future compatability
Example: `Bot.add_sticker_to_set()` doesn't pass kwargs into the `data` 

Opening this issue so we won't forget...

### PR DESCRIPTION
**Pull request by Eldinnie**
For all bot-methods that are not decorated with `@message`

fixes #733

### CODE REVIEW

**Comment by Eldinnie** [comment]
test_official will fail on 3.5 and 3.6 until #742 is merged

**Comment by tsnoam** [comment]
just waiting for travis to approve

**Comment by Eldinnie** [comment]
@tsnoam what's the difference by copying them? Also I just realised that it will be None if there are no kwargs. Is that a problem?

**Comment by tsnoam** [comment]
@Eldinnie 1. afaik it will always be a dict. an empty dict.
2. you know what? i was overthinking it. I'll revert my commit.

**Comment by Eldinnie** [comment]
Yes empty dict indeed

**Comment by Eldinnie** [comment]
Only expected test fail. Unfortunately there's not much we can do about the coverage drop...

**Pull request merged**
