### PR TITLE
Adjust sphinx docs to telegram.ext submodule

### PR DESCRIPTION
**Pull request by jh0ker**

### CODE REVIEW

**Comment by leandrotoledo** [comment]
@jh0ker Please also update README

**Comment by leandrotoledo** [comment]
Besides that, everything does look good!

**Comment by jh0ker** [comment]
Should I also update the examples to import from `telegram.ext`?

**Comment by leandrotoledo** [comment]
Good catch! I think you should.

**Comment by rahiel** [comment]
@jh0ker Looks good, there's only something weird with the formatting, search for `__Note:__` in the [readme](https://github.com/python-telegram-bot/python-telegram-bot/blob/ext-docs/README.rst#telegram-ext).

**Pull request merged**
