### PR TITLE
Fix Filters documentation

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by jh0ker** [comment]
Thank you :) Do you want to add yourself to [`AUTHORS.rst`](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/AUTHORS.rst) before I merge?

**Comment by jh0ker** [comment]
Actually, this fails on the flake8 pre-commit hook. To quote @bomjacob:

> I think that's the original reason I had for not including those MessageEntity in the first place, since the docs can't show it properly if you break it into two lines either...

If you can solve this without exceeding the maximum line length of 99 characters while still producing a nice-looking doc page, that would be great.

**Comment by Eldinnie** [comment]
You could also add `# noqa` at the end of the longer line to let flake8
ignore them

Op di 25 apr. 2017 om 10:49 schreef Jannes Höke <notifications@github.com>:

**Comment by jh0ker** [comment]
@Eldinnie That sounds reasonable to me

**Comment by jh0ker** [comment]
To make sure it doesn't show up in the rendered HTML page, it should also be prepended with `..` (rst comment). Not sure if this works inline though.

**Comment by revolter** [comment]
Yeah, that's some pretty hard line to break. Are you up to add the comment yourself? As it allows edits from maintainers.

**Comment by Eldinnie** [comment]
yes so to be complete: append the line that's too long with `.. # noqa: E501` to make it pass flake8's test but not show up in the docs.

**Comment by revolter** [comment]
I don't get what's wrong this time, coveralls is showing all errors, not only those added by this PR :-?

**Comment by jh0ker** [comment]
You can ignore the coveralls check for changes like this, it sometimes fucks up

**Comment by revolter** [comment]
Done

**Comment by jh0ker** [comment]
image
Sadly, it does not seem to work :/

**Comment by revolter** [comment]
Where is that screenshot from?

**Comment by jh0ker** [comment]
I cloned your repo/branch and built the documentation

**Comment by revolter** [comment]
With Sphinx?

**Comment by jh0ker** [comment]
Yes. `python setup.py build_sphinx`

**Comment by Eldinnie** [comment]
@jh0ker autodoc maybe ignores it... dunno how to make it ignored in the docs

**Comment by revolter** [comment]
Would this:

            >>> (
            >>>     Filters.text & (
            >>>         Filters.entity(MessageEntity.URL) | Filters.entity(MessageEntity.TEXT_LINK)
            >>>     )
            >>> )

be acceptable? I think it also helps the readability by separating those 3 ending parenthesis.

**Comment by jh0ker** [comment]
I think that is a reasonable compromise. Please use `...` instead of `>>>` to denote the continued expression over multiple lines

**Comment by revolter** [comment]
I didn't know the exact syntax, I added now the commit.

**Comment by revolter** [comment]
Why are there so many `unhashable type: 'list'` errors in Travis?

**Comment by Eldinnie** [comment]
@revolter see #579

**Comment by Eldinnie** [comment]
I overhauled filters docs in #728 so closing this one.

**Pull request closed without merging**
