### PR TITLE
Add support for Socks5 proxy.

### LINKED ISSUE #517: support socks5 proxy.
First of all, everthing works well. Very thanks for your working on this awesome lib.

But in China, telegram is been blocked by gov. When deploying the bot in China, it's unable to reply message to the api server, can receive message from telegram.

I tried to set up a sock5 proxy, but failed. Is there any plan for supporting the sock5 proxy?

image

### PR DESCRIPTION
**Pull request by daimajia**
fix #517 

I'm not quite sure if I'm doing the right thing. 🤣 

Please comment if I'm making mistake. 🗣

### CODE REVIEW

**Comment by jh0ker** [comment]
It looks okay to me, did you do a manual test to see if it works for you?

**Comment by jh0ker** [comment]
BTW, you also have to edit the requirements accordingly (at least for travis) to prevent this error:
```
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/urllib3/contrib/socks.py:37: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies```

**Comment by daimajia** [comment]
@jh0ker Get it. Thanks for your tips.

**Comment by daimajia** [comment]
@jh0ker I did a manual test, and it works well.

**Comment by daimajia** [comment]
@jh0ker Any idea on [this issue](https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/201115666#L878-L889)?

**Comment by jh0ker** [comment]
@daimajia that is expected behavior, no need for your to worry

**Comment by daimajia** [comment]
BTW. [This issue](https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/201115666#L933-L940)

It looks all right for this PR. 😃

**Comment by jh0ker** [comment]
It would be preferred to list the dependency as an extra dependency, similar to `ujson`. You'd have to put it in `setup.py`. To prevent import errors on systems where it is not installed, I recommend you move the import into the `if` that starts in line 97 of `request.py`

**Comment by daimajia** [comment]
Good suggestion. I'll finish it ASAP.

**Comment by daimajia** [comment]
@jh0ker Remove the dependency from `requirements.txt`, right?  I'm not sure.

**Comment by daimajia** [comment]
@jh0ker How about now?

**Comment by jh0ker** [comment]
@daimajia yes, please

**Comment by daimajia** [comment]
@jh0ker Done, please check it.

**Comment by tsnoam** [comment]
@daimajia Thank you for your good work. That's something we'd really like.
1. I performed a very minimal test for your PR with ssh socks5 proxy and it works for me :+1: 
2. There are two minor things I would like to fix before I merge (and already have the commits ready) but I can't push to your repo/branch (and save the ping pong of asking you to do them). Can you allow the maintainers to push? See: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by daimajia** [comment]
image

right?

**Comment by tsnoam** [comment]
@daimajia 
yes, it is good. must have been my fault earlier. anyway i pushed my small changes and after Travis will finish unitests, I believe we'll be able to merge.

**Comment by daimajia** [comment]
@tsnoam Thanks. ❤️

**Comment by tsnoam** [comment]
@daimajia 
sorry for the delay. the failure in CI is irrelevant to your changes, so I'm merging the PR.
Thanks for the good work.
BTW, I see that you haven't added yourself to `AUTHORS.rst`. If you'd like being mentioned there, feel free to send a second PR.

**Comment by daimajia** [comment]
@tsnoam Thanks, I'm pretty willing to add myself to the contributors list, I'm proud of contributing to this lib. 😊

**Pull request merged**
