### PR TITLE
Add wait longer for expected jobs to run in tests.

### PR DESCRIPTION
**Pull request by francamacdowell**
I saw that one guy created a good idea for the tests and disappear.
So I'm sending the PR idea.
Solving #957

### CODE REVIEW

**Comment by jsmnbom** [comment]
Thanks a lot for taking the time to make this contribution! :D
Currently it doesn't quite fix everything that we'd like, you're very welcome to simply add more commits to your branch if you'd like to keep working on this.

We are go need to do this for every single one of the jobqueue tests, not just test_run_once. This means you'll probably also have to put the job_ran = threading.Event() inside the reset fixture so it is reset for every test that is run. Once this is done, try also removing the @skipif line that we have on the class, since that should no longer be needed :D

**Comment by Eldinnie** [comment]
I would like encourage you to fix the rest of the tests. Verhy welcome!

**Comment by Ambro17** [comment]
Hi, i'm interested in refactoring these tests but i don't want to overlap with other dev. Is it okay if i take it?

**Comment by francamacdowell** [comment]
Yes, It is. You can take it

**Comment by Bibo-Joshi** [comment]
Closing in favour of of #1357

**Pull request closed without merging**
