### PR TITLE
Update updater.py

### PR DESCRIPTION
**Pull request by shouya**
fixing python-telegram-bot/python-telegram-bot#275

### CODE REVIEW

**Comment by jh0ker** [comment]
Travis is failing because of `flake8`. We moved to 99 characters per line instead of 79 and didn't update the configuration. I updated the config to reflect the changes and restarted travis tests.

**Comment by jh0ker** [comment]
A timeout is not really what we want here - if there are no new updates, we don't want to wait 10 seconds but return immediately. I think what we should do here is increase `network_delay`, which is not sent to the telegram servers but instead only used for the `urlopen` timeout. Still, it might happen that the `urlopen` call times out, so we should catch that exception and move the `_clean_updates` call to the bootstrap phase, like `_set_webhook`.

**Comment by shouya** [comment]
If there is no new updates, definitely it shouldn't wait for 10 secs. An expected way is to return `[]` or `None` from `getUpdates`. Not sure how python-telegram-bot deal with this. Probably tuning `network_delay` is a more proper way to do. Feel free to close my PR if it doesn't meet the requirement. I just wanted to point out the bug over there.

**Comment by jh0ker** [comment]
An empty list would indeed be the expected result. I'll close this PR and send a new one tomorrow. Thank you for pointing out the bug :)

**Pull request closed without merging**
