### PR TITLE
imlemented crontab based repeating job for jobqueue

### PR DESCRIPTION
**Pull request by marekyggdrasil**
This is a pull request for a draft implementation of crontab based repeating jobs, more details in following issue where I made my proposal for this feature: https://github.com/python-telegram-bot/python-telegram-bot/issues/1337

### CODE REVIEW

**Comment by marekyggdrasil** [comment]
@Bibo-Joshi I understand there is a release plan, I have not abandoned this change, I can see tests are no longer passing due to merges that happen in the meantime.

If you guys decide to merge this PR, just ping me and I'll update the PR to be compatible and mergeable with most recent state of the repo.

**Comment by Bibo-Joshi** [comment]
> @Bibo-Joshi I understand there is a release plan, I have not abandoned this change, I can see tests are no longer passing due to merges that happen in the meantime.
> 
> If you guys decide to merge this PR, just ping me and I'll update the PR to be compatible and mergeable with most recent state of the repo.

Glad to hear! We'll need to figure out what our plan for the next releases is, though, so it will probably take a while until we get back to this PR …

**Comment by marekyggdrasil** [comment]
@Bibo-Joshi absolutely, that is understandable, in case if you guys decide to merge it to next release and I won't be responsive feel free to reach me in DM. Good luck!

**Comment by Bibo-Joshi** [comment]
TL;DR: Closing in favor of #1981 

After internal discussion, we came to the conclusion that we don't want to continue implementing scheduling logic on our own and instead rely on a 3rd party library for that (see #1936, #1981).
One of the upsides is, that a cron logic is already included.
We appreciate the effort that was put in this PR and hope that you'll find the new `JobQueue` useful once it's finished :)

**Comment by marekyggdrasil** [comment]
@Bibo-Joshi looking forward to try out the new `JobQueue`!

**Pull request closed without merging**
