### PR TITLE
Make error output more clear for too big uploads.

### PR DESCRIPTION
**Pull request by alateas**
I have faced unclear error output('Invalid server response') when tried to send big audio ~ 200mb via bot.send_audio. It was hard to understand that now you can upload files up to 50 MB using telegram api. So my small fix makes error output more clear by doing two things:
 - moving data pasing block after error checking
 - adding 413(Request Entity Too Large) status to check

### CODE REVIEW

**Comment by jh0ker** [comment]
Please see the travis log

**Comment by alateas** [comment]
Ok, I see, there is a lot of connections with this error handling part. Client code and unit tests expect a certain behavior.  So i will think ho I can eject 413 error message gentle way.

**Comment by jh0ker** [comment]
@alateas That's not the point. The point is that you moved the part where message is parsed further down, and now other parts of the code that need that variable don't work

**Comment by jh0ker** [comment]
Oh I'm sorry, you already fixed that :smile:

**Comment by alateas** [comment]
Reason of moving block of http error handling( https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/request.py#L191-L200 ) up is that this block will never be executed. Because if we, for example, get a 502 http error, any way data will parsed in 187 line and json parsing will raise ValueError in 134 line.

Any way my last fix was wrong too :)

**Comment by Eldinnie** [comment]
Can't you insert the check between the 200-209 check and the message parsing in the original file? It doesn't need the message.

**Comment by alateas** [comment]
I can, but this check the similar with other http error checs at lines 191-200, will be strange to separate 413 http error check.

**Comment by tsnoam** [comment]
@alateas I have a fix for your fix :-)
however, it seems that you haven't allowed edits to your branch by maintainers. Can you please allow it and I'll push? See:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by alateas** [comment]
@tsnoam Good news! Actually I have allowed maintainers edits, I rechecked it right now.

**Comment by tsnoam** [comment]
I failed to push my commit. I wonder if I do something wrong.
Anyhow, I just edited the code using the github web interface. I hope I haven't made any typo.
Now we'll wait for travis to see if it works.

**Comment by Eldinnie** [comment]
I I see this correctly. The way it is in the latest commit it will never raise an error if there is an error but not in one of the error codes. Shouldn't we add an
```
else:
  raise NetworkError(message)
```
at the bottom?

**Comment by Eldinnie** [comment]
Nevermind, it just fell off the screen. It looks good to me.

**Comment by tsnoam** [comment]
@alateas thanks for your contribution.

**Pull request merged**
