### PR TITLE
introduce constants module

### PR DESCRIPTION
**Pull request by rahiel**
A module with constants of the Telegram network. The constants are tested, so we'll now when Telegram will change them...

### CODE REVIEW

**Comment by jh0ker** [comment]
**Further suggestions**

Message limits:
- `MAX_MESSAGES_PER_SECOND = 30`
- `MAX_MESSAGES_PER_SECOND_PER_CHAT = 1`
- `MAX_MESSAGES_PER_MINUTE_PER_GROUP = 20`

File sizes
- `MAX_FILESIZE_UPLOAD = 50000000` (50MB)
- `MAX_FILESIZE_DOWNLOAD = 20000000` (20MB)
- There may be a special limit (size or length) for voice messages, I'll check that out

Others:
- `SUPPORTED_WEBHOOK_PORTS = [443, 80, 88, 8443]`

**Comment by MWeesenaar** [comment]
Looks good to me!
Tests run and are green.

**Comment by rahiel** [comment]
> `MAX_MESSAGES_PER_SECOND_PER_CHAT = 1`

From where was this? My bot can send me 30 messages per second.

**Comment by jh0ker** [comment]
@rahiel from the bot FAQ: >When sending messages inside a particular chat, avoid sending more than one message per second. We may allow short bursts that go over this limit, but eventually you'll begin receiving 429 errors.

**Pull request merged**
