### PR TITLE
Simplification of boolean checks

### PR DESCRIPTION
**Pull request by saschalalala**
While I worked on the other pull request, I saw that the boolean checks for the payment functions are somewhat unpythonic (See https://www.python.org/dev/peps/pep-0008/#programming-recommendations the last bullet point for reference).

### CODE REVIEW

**Comment by Eldinnie** [comment]
Look good, let's wait if Travis aggrees

**Comment by jh0ker** [comment]
It was discussed in the developer group that while this change is good, we still should enforce `ok` to be a `bool` because else, we'll run into problems with the JSON encoding. So it would be nice if you added `ok = bool(ok)` to make sure of that.

**Comment by saschalalala** [comment]
Will do.

**Comment by saschalalala** [comment]
This should do it, I guess. Or should I add a comment for clarification?

**Comment by jh0ker** [comment]
Thanks, it looks good :)

**Pull request merged**
