### PR TITLE
Invite link convenience functionality

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
adds nome convenience functionality around chat invite links. nothing urgent.

### Checklist for PRs

- [x] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [x] Created new or adapted existing unit tests
- [ ] Added myself alphabetically to `AUTHORS.rst` (optional)
- [x] Added new classes & modules to the docs

### CODE REVIEW

**Review by harshil21 — APPROVED** [review]
nice feature, but is there a reason why we don't use the other parameters of `ChatInviteLink` here too? Similar to how we do in [`send/edit_location`](https://github.com/python-telegram-bot/python-telegram-bot/blob/3164c0b42b0df7e523b449e559e291550a52413a/telegram/_bot.py#L1465)

**Comment by Bibo-Joshi** [comment]
> nice feature, but is there a reason why we don't use the other parameters of `ChatInviteLink` here too? Similar to how we do in [`send/edit_location`](https://github.com/python-telegram-bot/python-telegram-bot/blob/3164c0b42b0df7e523b449e559e291550a52413a/telegram/_bot.py#L1465)

TBH, I hadn't really thought about it, but interesting idea! you'd do something like e.g.

```python
if isinstance(invite_link, ChatInviteLink):
    expire_date = expire_date or  invite_link.expire_date
```
? That could work. If we want to allow users to e.g. delete the `expire_data`, we'd have to maybe do something like
```python
def edit_chat_link(…, expire_date = DEFAULT_NONE):
    if isinstance(invite_link, ChatInviteLink):
         expire_date = expire_date or invite_link.expire_date
    expire_data = DefaultValue.get_value(expire_date)
```
such that `edit_chat_link(chat_link_instance, expire_date=None)` allows to explicitly set `expire_date` to `None`.
And we'd have to mind that one could want to override `member_limit` with `creates_join_request` and vice versa.

At first glance, I'm not sure if the added convenience is worth the added complexity of the method. What do you think?

**Comment by harshil21** [comment]
ugh, in that case probably best to leave it like this. Not to mention documentation will also increase in complexity.

**Review by Poolitzer — APPROVED** [review]
Changes look good.

**Pull request merged**
