### PR TITLE
Remove some debug prints. IMHO there is still enough debug printing a…

### PR DESCRIPTION
**Pull request by springjools**
…nd if there is too much of it, the relevant parts are harder to find.

### CODE REVIEW

**Comment by leandrotoledo** [comment]
I agree with removing the DEBUG log from telegram/bot.py message decorator.
About the telegram/ext/jobqueue.py, I'll leave to @jh0ker to provide some input as he did some rework there.

**Comment by jh0ker** [comment]
Yes, please take a look at #307 
The whole ticking thing has been removed, the job queue now sleeps when there are no jobs due. This should reduce spam by a lot. If you still think it's too much, please leave a comment on that PR

**Comment by leandrotoledo** [comment]
Hi @springjools, so please rollback telegram/ext/jobqueue.py and instead a comment, remove lines 108 and 111 from bot.py and this will be good to be merged.

Thank you!

**Comment by leandrotoledo** [comment]
Marking as obsolete.

**Pull request closed without merging**
