### PR TITLE
Dispather command processing fix(#200).

### PR DESCRIPTION
**Pull request by shelomentsevd**
See description in issue #200

### CODE REVIEW

**Comment by leandrotoledo** [comment]
Restarting build, seems like Travis wants attention, to be confirmed.

**Comment by leandrotoledo** [comment]
So, this is the reason it's failing:
> telegram/dispatcher.py:551:80: E501 line too long (82 > 79 characters)

So, my only concern with that is casting the string to UTF-8 (assuming it will be always it). We got rid of any decodes/encodes from our codebase long ago to avoid such conflicts, one approach would be expanding an if-block to check if this conditions applies and then, finally, cast/split/cast back to unicode. But that would be a workaround for something that doesn't necessarily is on us. Let's hear what @jh0ker and @njittam have to say about it.

I think it's also worth to report to Telegram Web this bug as well.

**Comment by shelomentsevd** [comment]
> I think it's also worth to report to Telegram Web this bug as well.
Not sure that is a bug.
I made new commit, because found solution without casting to UTF-8.

**Comment by leandrotoledo** [comment]
Nice! I liked this one better! Thanks for your contribution @shelomentsevd!
Merging, cheers!

**Pull request merged**
