### PR TITLE
removing legacy CI files

### PR DESCRIPTION
**Pull request by Poolitzer**

### CODE REVIEW

**Comment by septatrix** [comment]
Searching in the source code still yields some references to travis and appveyor. Should these also be removed?

```console
$ grep --line-number --ignore-case appveyor -R *
CHANGES.rst:621:- Unitests are now also running on AppVeyor (Windows VM).
tests/test_jobqueue.py:41:@pytest.mark.skipif(os.getenv('APPVEYOR'), reason="On Appveyor precise timings are not accurate.")
tests/test_messagequeue.py:28:@pytest.mark.skipif(os.getenv('APPVEYOR'), reason="On Appveyor precise timings are not accurate.")
tests/test_bot.py:495:    @pytest.mark.skipif(os.getenv('APPVEYOR') and (sys.version_info < (3, 6)),
tests/test_bot.py:496:                        reason='only run on 3.6 on appveyor')

$ grep --line-number --ignore-case travis -R *
CHANGES.rst:157:- travis.yaml: TEST_OFFICIAL removed from allowed_failures.
CHANGES.rst:161:- Add Python 3.8 (RC version) to Travis testing matrix (`#1543`_).
tests/test_updater.py:147:        port = randrange(1024, 49152)  # Select random port for travis
tests/test_updater.py:183:        port = randrange(1024, 49152)  # Select random port for travis
tests/test_updater.py:207:        port = randrange(1024, 49152)  # Select random port for travis
tests/test_updater.py:227:        port = randrange(1024, 49152)  # Select random port for travis
tests/test_updater.py:282:        port = randrange(1024, 49152)  # select random port for travis
tests/conftest.py:35:TRAVIS = os.getenv('TRAVIS', False)
tests/conftest.py:37:if TRAVIS:
tests/conftest.py:38:    pytest_plugins = ['tests.travis_fold']
tests/travis_fold.py:32:        terminalreporter.write('travis_fold:start:plugin.{}\n{}\n'.format(plugin_name, text))
tests/travis_fold.py:34:        terminalreporter.write('travis_fold:end:plugin.{}\n'.format(plugin_name))
tests/travis_fold.py:81:        terminal.write('\ntravis_fold:start:{}\r'.format(name.split('::')[1]))
tests/travis_fold.py:82:        terminal.write('travis_time:start:{}time\r'.format(name.split('::')[1]))
tests/travis_fold.py:92:            terminal.write('\n\ntravis_fold:end:{}'.format(name.split('::')[1]))
tests/travis_fold.py:93:        terminal.write('\rtravis_time:end:{}time:'
tests/travis_fold.py:96:        time.sleep(0.001)  # Tiny sleep so travis hopefully doesn't mangle the log

**Comment by Bibo-Joshi** [comment]
Yes, I think they can be removed as well (except the lines from the changelog, of course). Would you care to pr?

**Comment by tsnoam** [comment]
@Bibo-Joshi Travis fold might still be used.

**Comment by Bibo-Joshi** [comment]
@tsnoam The config.py only uses it when tests are running on Travis

**Comment by tsnoam** [comment]
@Bibo-Joshi In that case, I have no objections to remove :)

**Pull request merged**
