### PR TITLE
Use a Composite Action for Testing Type Completeness

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
outsources the code to a reusable component. I'm also using this in `aiorem` now.

### CODE REVIEW

**Comment by harshil21** [comment]
Interesting. Are there any functional changes to it apart from it being outsourced?

Also, can you deliberately change something so that the test fails (so that I know it's actually working) 😅

**Comment by Bibo-Joshi** [comment]
> Interesting. Are there any functional changes to it apart from it being outsourced?

currently PTB allows a 0.1% decrease of type completeness - I threw that out for now.

> Also, can you deliberately change something so that the test fails (so that I know it's actually working) 😅

Will do :)

**Comment by Bibo-Joshi** [comment]
well, shit :D

**Comment by Bibo-Joshi** [comment]
all, right, here we go. failing workflow at https://github.com/python-telegram-bot/python-telegram-bot/actions/runs/9872648792/job/27263177990?pr=4367 caused by https://github.com/python-telegram-bot/python-telegram-bot/pull/4367/commits/7de254138b591eb79b66e8aa9fb534731593ccec

**Review by harshil21 — APPROVED** [review]
good thing that was tested!

**Pull request merged**
