### PR TITLE
pollbot.py example was sending the poll to the effective_user and not…

### PR DESCRIPTION
**Pull request by lrezende**
It's about pollbot.py example. The poll command was sending the poll to the update.effective_user.id... I think it should be update.effective_chat.id so multiple chat members could answer the poll.

### CODE REVIEW

**Comment by Poolitzer** [comment]
Well the answers are only received on a user basis, not chat one, so the "answer" will be send in a private chat anyway. I dont really see a big gain of your PR but I dont mind it either

**Comment by lrezende** [comment]
I think the pollbot example was meant to have some answers in the same poll_id...
```
# Close poll after three participants voted
if context.bot_data[poll_id]["answers"] == 3:
```
If you send the poll to a private chat(user) it will never receive more than one answer.
Correct me if I'm wrong. I'm just starting with ptb and open source contribution.

**Comment by Poolitzer** [comment]
No yeah I guess you are right, never thought about running it in a group, but that change is OK.

**Comment by Bibo-Joshi** [comment]
pytest fails obviously unrelated and we can ignore the examples warning, as there is nothing new in the example. Merging.
Thanks for the contribution @lrezende !

**Pull request merged**
