### PR TITLE
Add chain methods to improve keyboard markup creating experience

### PR DESCRIPTION
**Pull request by Oakento**
Function of keyboard markup has been enhanced by classmethods, yet it still needs creation of list-of-button-list in advance dealing with multiple rows of buttons. 

Methods `add_button`, `add_row`, `add_from_markup` added to `InlineKeyboardMarkup` and `ReplyKeyboardMarkup` can be called by chain to add button to the markup. `add_from_markup` method permits modularization of buttons to plug in as an existing markup.

* To support method chaining, I changed `inline_keyboard` to a optional argument. It seems having no adverse effect by now.

### CODE REVIEW

**Comment by Bibo-Joshi** [comment]
Hi! Thanks for the PR :)

TBH I'm not sure if I see the benefit of it. It seems to me that especially `add_button` and `add_row` will not lead to reduction of code length. I do see a use case for merging existing keyboards. But I guess that's a small one and I don't know if 

```python
keyboard = old_kb[:ixd].extend(new_keyboard).extend(old_kb[idx+1:])
```

justifies it's own method …
But maybe I'm just not understanding what you indented this for. Could you maybe give an example?

I'd also like to check, what the other devs think of it. @Poolitzer @tsnoam do you have an opinion?

**Comment by Oakento** [comment]
These three methods are in concern of using keyboard markup without directly operating the behind keyboard of two-dimensional list, which provides encapsulation for the behind structure, that improves experiences programming with IDE. 

As for the `add_from_markup` method, you remind me of `extend` method of list((((；ﾟДﾟ))))))). Sorry about that, I should do a full study before working on list-related jobs.

**Comment by Bibo-Joshi** [comment]
> These three methods are in concern of using keyboard markup without directly operating the behind keyboard of two-dimensional list, which provides encapsulation for the behind structure, that improves experiences programming with IDE.

My point is that I don't see any benefit of something like

```python
keyboard = ReplyKeyboardMarkup()
keyboard = keyboard.add_row([btn1, btn2, btn3])
keyboard = keyboard.add_row([btn4, btn5, btn3])
```
over
```python
keyboard = ReplyKeyboardMarkup([
    [btn1, btn2, btn3], [btn4, btn5, btn3]
])
```
But again, this may be because I don't really understand your use case and the other devs might have a different opinion :)

> As for the `add_from_markup` method, you remind me of `extend` method of list((((；ﾟДﾟ))))))). Sorry about that, I should do a full study before working on list-related jobs.

No problem, that's what reviews are for :D

**Comment by Oakento** [comment]
```python
keyboard0 = InlineKeyboardMarkup([[btn0]])    ## if there is an existing keyboard, for example, received from update, that I 
                                              ##intend to use it as a base of new markup

### using add_* methods to edit it
keyboard1 = keyboard0.add_button(btn1).add_button(btn2).add_row().add_button(btn3).add_button(btn4, from_row=0)

### manage by list editing
inline_keyboard1 = keyboard0.inline_keyboard + [[btn1, btn2], [btn3]]
inline_keyboard1[0].append(btn4)
keyboard1 = InlineKeyboardMarkup(inline_keyboard1)

##################
## <btn0><btn4> ##
## <btn1><btn2> ##
## <---btn3---> ##
##################
```
It reduce pack and unpack process.

**Review by Poolitzer — CHANGES_REQUESTED** [review]
Alright.

First of all, @Oakento, thanks for this PR. I can see the work you put into it. And I am sorry for letting you wait so long with my review.

I went through your changes and made some comments here and there. They are not the main part of this message.

The main part is @Bibo-Joshi and mine hesitation. "Do we really need this functionality in our library" is the question we as maintainers have to ask ourselves. From building my own bots, I know I would not use this method. My own keyboard generator are easier to just reuse then adding the changed buttons with your suggested methods.

That does not mean other people wouldn't use it though. Especially for simpler markup, I can see people just wanting to use an `add_button()`. So from my side, the suggested changes are approved, just not your code yet.

In general and for the next time, please open an issue first and discuss it with the maintainers first. That way, if we end up disapproving your suggestion, your efforts would not have been wasted.

I would suggest you to wait for some other maintainer to give you the full go and then go through your code again and implement/think about my suggestions :)

**Comment by Bibo-Joshi** [comment]
Hi! Sorry for taking my time with a reply. We discussed your PR again, but we still have the feeling that it's too specific for the main lib. However it indeed might still be useful for other users and you're very welcome to PR over at [ptbcontrib](https://github.com/python-telegram-bot/ptbcontrib) :) If you have questions on that, feel free to reach out on telegram (@BiboJoshi). In any case, we appreciate that you made the effort for the PR! Community contributions keep the project alive, after all :)

**Pull request closed without merging**
