### PR TITLE
Add manual darkmode to docs

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
So, I was procastinating and noticed that [pillows docs](https://pillow.readthedocs.io/en/stable/) have a dark mode that's activated when your browser does the `prefers-color-scheme` thingy. My eyes like dark mode, so I had a look at how they did that.

Apparently the RTD theme won't have a native dark mode for a while (readthedocs/sphinx_rtd_theme#224 is open since 2015, so ~as old as PTB). So they just took the https://darkreader.org Chromium-Extension and exported the CSS generated by that. Looks neat IMHO. Can be previewed at https://python-telegram-bot.readthedocs.io/en/docs-dark-mode/. If you don't find the dark-mode setting in your browser, here are some screenshots:

<details>
  <summary>Click to expand</summary>
  <p>

  image
  
  image
  
  image
  </p>
</details>

Alternative approaches would be to go with different sphinx templates like [Furo](https://pradyunsg.me/furo/reference/), but I actually like the RTD theme and this manual approach isn't maintenance-heavy.

Obviously this is anything but pressing, but still nice-to-have IMO. If you like it, we can merge, if not I won't be too sad 🙂

### CODE REVIEW

**Comment by harshil21** [comment]
Definitely like the dark mode, since we're improving the docs anyway, how about these features/changes (maybe in another PR?):

- Make the list of classes in `index.rst` a dropdown one, so that the user is less overwhelmed at first look and it's easier to what's where. Perhaps [this setting](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-collapse_navigation) can help?

- Looks like we can also [change where the 'edit on github' url](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-github_url) points to (closing #2478). We can just link it to the corresponding file since most of our doc pages are from one file. Might have to do this for every file though.

- [Styling the external links](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-style_external_links) might look nice. Dunno how it looks like tho.

**Comment by Bibo-Joshi** [comment]
Nice ideas @harshil21 ! the external-links thingy was easy, pushing that directly to doc-fixes in a sec.

`edit on github`: IISC that would require either manually inserting `:github_url: https://github.com/ptb/ptb/blos/master/telegram/…` in each file or doing something hacky as proposed at https://github.com/readthedocs/sphinx_rtd_theme/issues/465#issuecomment-521272830, see https://github.com/peterjc/thapbi-pict/commit/f14b1df17ed3faf382a63095aa6e22f519e71957 . IMO the first is tedious & the second error-prone (and will probably break at some point). As I personally don't see a great value, I won't try to get that to work - but also won't stand in the way of it :) 

regarding the reference list: I've played around a bit, but didn't find a completey satisfactory solution. The best I could do was adding a `:hidden:` to the `toctree::` directives in `index.rst` which hides doesn't render them on the start page but still includes them in the TOC in the navigation bar. Don't know if that's what we want …

**Review by VChernomYA — APPROVED** [review]

**Comment by VChernomYA** [comment]
[](https://github.com/telegramdesktop/tdesktop/pull/16185/files)

**Review by Poolitzer — APPROVED** [review]
LGTM

**Review by harshil21 — APPROVED** [review]

**Pull request merged**
