### PR TITLE
consistent TelegramError exceptions for Bot.getMe()

### LINKED ISSUE #134: Bot.getMe() raises inconsistent exceptions
as agreed in the chat, all exceptions raised should be TelegramError (or similar exceptions)

these are the (inconsistent) exceptions I've seen:

```python
>>> telegram.Bot('not-probably-formatted-token').getMe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 176, in getMe
    result = request.get(url)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 67, in get
    return _parse(result)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 48, in _parse
    data = json.loads(json_data.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3621: ordinal not in range(128)

>>> telegram.Bot((9 * '1') + ':' + (35 * 'x')).getMe()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 126, in decorator
    result = func(self, *args, **kwargs)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/bot.py", line 176, in getMe
    result = request.get(url)
  File "/home/tsnoam/.local/lib/python2.7/site-packages/telegram/utils/request.py", line 65, in get
    result = urlopen(url).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

### PR DESCRIPTION
**Pull request by tsnoam**
fixes #134

### CODE REVIEW

**Comment by rahiel** [comment]
Looks good! Don't forget to add your name to [AUTHORS](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/AUTHORS.rst).

**Comment by rahiel** [comment]
@tsnoam the travis build is failing on `_valid_token`. I say we can do without that method, because Telegram will alert the user when the token is invalid anyway, no need for us to do it. Especially as it could incorrectly say a token is invalid like it did now.

**Comment by tsnoam** [comment]
@rahiel I added the test for a reason - in case of a not well formatted token, the error from the server will not be a json, but rather an html page (the documentation for the bot API).
Such a webpage will cause a wrong message in the TelegramError exception. 
I think that what I'll do instead is fix the unitests to bypass that specific validation, and write new unitests to actually test it.

(and also I'll update the AUTHORS file)

**Comment by tsnoam** [comment]
changes with the new PR:
* use functools.wrap for _try_except_req decorator
* added self to AUTHORS
* fixed bug in _valid_token -> thanks to unitests now working
* fix unitests to work with token validator
* gitignore: for files generated by unitests

**Comment by tsnoam** [comment]
pushed fix for python3...

**Comment by jh0ker** [comment]
Hey, it seems like the unit tests fail for Python 2.6, because there is an assert function missing, that you're not using (there is no regexp in the String you're testing for, so you could just use `assertRaises`). 

All the other changes seem very neat, at a first glance! Thank you very much for your work :)

**Comment by tsnoam** [comment]
@jh0ker 
following our chat - 
* aligned Updater.__init__ prototype to be more consistent
* added unitests to cover the changes as of above
* the accidentally removed str.capitalize() on api_error exceptions is now back

**Comment by jh0ker** [comment]
Thank you very much, Noam! :)

**Pull request merged**
