### PR TITLE
Add convenience classmethods for InlineKeyboardMarkup (fixes #1186)

### LINKED ISSUE #1186: Using InlineKeyboardMarkup with one button without 2D list
### Steps to reproduce
```
reply_markup = InlineKeyboardMarkup(InlineKeyboardButton(text="TEST_BUTTON", url="t.me/TEST"))
bot.send_message(chat_id=chat_id, text="TEST_MESSAGE", reply_markup=reply_markup)
```

### Expected behaviour
A message appears with the TEST_MESSAGE text and the TEST_BUTTON button
image

### Actual behaviour
`KeyError: 0` because the markup needs a compulsory of a list within a list (even for one button).

### Configuration
**Operating System:** Win10 1803
**Version of Python, python-telegram-bot & dependencies:**
```
python-telegram-bot 10.1.0
certifi 2018.01.18
future 0.16.0
Python 3.6.2
```
### Logs
```
2018-08-12 12:42:19,317 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "E:\python362\lib\site-packages\telegram\ext\dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "E:\python362\lib\site-packages\telegram\ext\commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "E:\bobermod\bot.py", line 17, in start
    bot.send_message(chat_id=update.message.chat_id, text="TEST_MESSAGE", reply_markup=reply_markup)
  File "E:\python362\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "E:\python362\lib\site-packages\telegram\bot.py", line 81, in decorator
    data['reply_markup'] = reply_markup.to_json()
  File "E:\python362\lib\site-packages\telegram\base.py", line 57, in to_json
    return json.dumps(self.to_dict())
  File "E:\python362\lib\site-packages\telegram\inline\inlinekeyboardmarkup.py", line 47, in to_dict
    for inline_keyboard in self.inline_keyboard:
  File "E:\python362\lib\site-packages\telegram\base.py", line 39, in __getitem__
    return self.__dict__[item]
KeyError: 0
```
### Improvement
It can be fixed by using list within a list:
`reply_markup = InlineKeyboardMarkup([[InlineKeyboardButton(text="TEST_BUTTON", url="t.me/TEST")]])`
**But it would be nice if it could be used with a single button without extra lists.**

### PR DESCRIPTION
**Pull request by expectocode**
Not sure if I got the docstring syntax right - how can I check this?

### CODE REVIEW

**Comment by expectocode** [comment]
@Lonami Good point, that might make more sense. As is, I directly implemented the idea from https://github.com/python-telegram-bot/python-telegram-bot/issues/1186#issuecomment-426226667

**Comment by jsmnbom** [comment]
@expectocode I think I agree with @Lonami here. Especially since I would have assumed that `from_single_line` did columns not rows, as that seems more useful to me.

Would you live to go ahead and rename + add a column one?

**Comment by expectocode** [comment]
Yeah, I'll get on that :+1:

**Comment by jsmnbom** [comment]
Thanks a lot for this PR @expectocode, and even more for changing it up again :D
Since this is your first PR I wanted to make it simple for you, and added some tests and make it work with replykeyboardmarkup, instead of once again asking you.
Hope to see more code etc. from you in the future.

**Comment by expectocode** [comment]
You're welcome! Thanks for working on this too and I'm glad I could contribute.

**Pull request merged**
