### PR TITLE
Add 3.7 to travis

### PR DESCRIPTION
**Pull request by jsmnbom**
See travis-ci/travis-ci#9815 for workaround discussion

### CODE REVIEW

**Comment by Eldinnie** [comment]
I personally think the second option mentioned in the linked thread looks cleaner:

```
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
```

**Comment by Eldinnie** [comment]
While we're at it, maybe add 3.7 on appveyor aswell

**Comment by Eldinnie** [comment]
adding 
```
- PYTHON: "C:\\Python37"
```
to the matrix should do the trick

**Comment by tsnoam** [comment]
@Eldinnie Why sudo=true?

**Pull request merged**
