### PR TITLE
Improve and expand CallbackQuery shortcuts

### LINKED ISSUE #2171: [FEATURE] CallbackQurey.delete_message
missed that in #2043

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
closes #2171

### CODE REVIEW

**Review by Poolitzer — CHANGES_REQUESTED** [review]
When inline message id is set and a user is calling delete(), the not really helping error `AttributeError: 'NoneType' object has no attribute 'chat_id'` is presented. Why not raise a custom one? At least put that in the docs.

And also, why delete_message()? With the message class, we just call it delete. I prefer that its way shorter (what a shortcut is all about imo)

**Comment by Bibo-Joshi** [comment]
> And also, why delete_message()? With the message class, we just call it delete. I prefer that its way shorter (what a shortcut is all about imo)

I guess you're right. Just copied from the other shortcuts. Actually, if we're at it, we can replace `self.bot.edit_*` calls with `self.message.edit_*`.

If we document `CQ.delete_message()` as shortcut for `callback_query.message.delete()`, would you be fine with leaving the error as is? we don't raise custom errors anywhere else …

**Comment by Poolitzer** [comment]
"anywhere else" can something like this happen, outside of this class? I would be fine not doing it, but I think overall custom errors would be an improvement.

**Comment by Poolitzer** [comment]
okay but you didnt change delete_message to delete, intentional?

**Comment by Bibo-Joshi** [comment]
> okay but you didnt change delete_message to delete, intentional?

uh, yes. I didn't understand your comment as "rename CQ.delete_message to CQ.delete", but as "why are you using `bot.delete_message` instead of `message.delete` xD
 but anyway I wouldn't wanna reanem to `CQ.delete`. Comparing with `CQ.answer` that would impley deleting the CQ … also we named all the other shortcuts `CQ.edit_message_*` and not `CQ.edit_*`. with a decent IDE, the shortcutiness is provided by autocomplete anyway …

**Review by Poolitzer — APPROVED** [review]

**Comment by Poolitzer** [comment]
LGTM then

**Pull request merged**
