### PR TITLE
All api 4.2 and 4.3 changes

### PR DESCRIPTION
**Pull request by Eldinnie**
Tests and coverage check needed

### CODE REVIEW

**Comment by AyraHikari** [comment]
Hello, i test that branch, and starting editing my bot script for future update.
But i got an error:
```
Traceback (most recent call last):
  File "/home/ayra/bot/my/__main__.py", line 535, in process_update
    handler.handle_update(update, self)
TypeError: handle_update() missing 1 required positional argument: 'check_result'
```
My script is
```
for handler in (x for x in self.handlers[group] if x.check_update(update)):
                handler.handle_update(update, self)
                break
```

I don't know what check_result is mean, when i'm insert check_result="test", bot is not responding when i send a command /start.

Also there is no guide for that in [this guide](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-12.0#handler-changes).

Thank you

**Comment by Eldinnie** [comment]
ehm...
Why do you run this? Choosing which handler is/and ashould be done by the dispatcher. It might be helpfull if you shared all your code and the intention of what you;re trying to do.

**Comment by AyraHikari** [comment]
Sure, [here it is](https://github.com/AyraHikari/EmiliaHikari/blob/be067cbaed457571fc0fc5555f51506034d6016f/emilia/__main__.py#L535)

**Comment by Eldinnie** [comment]
@AyraHikari you rewrote the dispatchers <code>process_update</code> method. If you want to do that with the new version, you will have to make sure it works the same as <code>Dispatcher.process_update</code>.

**Comment by AyraHikari** [comment]
Oh i see, maybe i should rewrite all things since many of that deprecated.
Thank you for your response. Sorry for late reply

**Comment by madl-ash** [comment]
why is this not merged?

**Comment by Nukesor** [comment]
Would love to see this merged, especially since 4.4 is already out there!

**Comment by Bibo-Joshi** [comment]
I noticed, that an `telegram.loginurl.rst` file is missing for the docs.

**Pull request merged**
