### PR TITLE
Remove checks for None on assignement for opt args

### LINKED ISSUE #1594: [BUG] InlineKeyboardButton with switch_inline_query='' doesn't work
### Steps to reproduce
1. Send a message with a inline keyboard button with `switch_inline_query=''`
```
inline_btn = InlineKeyboardButton('inline button', switch_inline_query='')
print(inline_btn)
markup = InlineKeyboardMarkup([[inline_btn]])
update.message.reply_text('message with inline button', reply_markup=markup)
```
2. Output of the print statement:
`{'text': 'inline button'}`
along with error message: "Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard"

### Expected behaviour
The message should appear with the button as documented: "Can be empty, in which case just the bot’s username will be inserted."

### Actual behaviour
Message and button doesn't appear and error is thrown

### Configuration
**Operating System:**
Windows 10

**Version of Python, python-telegram-bot & dependencies:**

``$ python -m telegram``
python-telegram-bot 12.2.0
certifi 2019.09.11
future 0.18.1
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]

### Logs
```
{'text': 'inline button'}
WARNING - Update "..." caused error "Can't parse inline keyboard button: text buttons are unallowed in the inline keyboard"
```

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
As pointed out by @jh0ker in the dev-chat, the checks

```
if arg:
    self.arg = arg
```

are not necessary, since `TelegramObject.to_dict()` ignores `None` anyway.

Also Closes #1594

### CODE REVIEW

**Comment by tsnoam** [comment]
workflow fails on py3.5 & py3.7 on windows. need to investigate.

**Comment by tsnoam** [comment]
this PR can be moved to milestone 12.4 if fixing the CI will take too long.

**Comment by Bibo-Joshi** [comment]
Will try to investigate tomorrow

**Comment by Bibo-Joshi** [comment]
Tests succeed after restart. All I saw was something about set_webhook_info which should be unrelated ...

**Pull request merged**
