### PR TITLE
move botan from utils to contrib

### PR DESCRIPTION
**Pull request by rahiel**
Moves botan support to ext.

### CODE REVIEW

**Comment by leandrotoledo** [comment]
Maybe we should a backwards compatibility import to ``telegram.utils.__init__`` and warns, and by v5 remove it, like we did with all the ext classes in the past.

**Comment by rahiel** [comment]
> Maybe we should a backwards compatibility import to telegram.utils.__init__ and warns, and by v5 remove it, like we did with all the ext classes in the past.

I'm having some trouble with this, putting the following in `telegram.utils.__init__`:
```python
from telegram.ext.botan import Botan
```
breaks importing `NullHandler`:
```python
In [1]: import telegram
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c0c4e3ab5730> in <module>()
----> 1 import telegram

/home/rahiel/Code/telegram/python-telegram-bot/telegram/__init__.py in <module>()
     42 from .error import TelegramError
     43 from .inputfile import InputFile
---> 44 from .file import File
     45 from .nullhandler import NullHandler
     46 from .emoji import Emoji

/home/rahiel/Code/telegram/python-telegram-bot/telegram/file.py in <module>()
     22 
     23 from telegram import TelegramObject
---> 24 from telegram.utils.request import download as _download
     25 

/home/rahiel/Code/telegram/python-telegram-bot/telegram/utils/__init__.py in <module>()
----> 1 from telegram.ext.botan import Botan

/home/rahiel/Code/telegram/python-telegram-bot/telegram/ext/__init__.py in <module>()
     19 """Extensions over the Telegram Bot API to facilitate bot making"""
     20 
---> 21 from .dispatcher import Dispatcher
     22 from .jobqueue import JobQueue
     23 from .updater import Updater

/home/rahiel/Code/telegram/python-telegram-bot/telegram/ext/dispatcher.py in <module>()
     26 from queue import Empty
     27 
---> 28 from telegram import (TelegramError, NullHandler)
     29 from telegram.ext.handler import Handler
     30 from telegram.utils.deprecate import deprecate

ImportError: cannot import name 'NullHandler'

```
Same with relative import (`from ..ext.botan import Botan`)

**Comment by leandrotoledo** [comment]
#306 drops use of NullHandler, let's see how it goes.

**Comment by leandrotoledo** [comment]
#306 removed NullHandler by accident, we may have to reavaluete this.

**Comment by leandrotoledo** [comment]
Changed PR title and scope for moving those kind of libs to either `telegram.contrib` or `telegram.third_party`, this will be decided by the community on [telegram.me/pythontelegrambotgroup](http://telegram.me/pythontelegrambotgroup)

**Comment by leandrotoledo** [comment]
> 24h poll indicates contrib over third_party, as follows:

```
In the future, how would you like to import 3rd party libraries (like Botan.io, AddyBot.com etc)? Please pick one of the options below.

from telegram.contrib import Botan – 36
👍👍👍👍👍👍👍 78%

from telegram.third_party import Botan – 10
👍👍 22%

👥 46 people voted so far.
```

**Comment by rahiel** [comment]
Travis is finally happy, ready for final review.

**Comment by leandrotoledo** [comment]
I believe we also should include that to v4.2 and by v5 remove the warning? Thoughts?

**Comment by rahiel** [comment]
> I believe we also should include that to v4.2 and by v5 remove the warning? Thoughts?

I agree, we can also postpone removing the backwards compatibility if we move too fast.

**Pull request merged**
