### PR TITLE
Group filters

### PR DESCRIPTION
**Pull request by Eldinnie**
Add filters:
 - Filters.private (for messages in private chats)
 - Filters.group   (for messages in group chats)

### CODE REVIEW

**Comment by jh0ker** [comment]
Looks great :) II would like to request one change: Instead of string literals, could you use `Chat.PRIVATE` and similar constants?

**Comment by Eldinnie** [comment]
yes will do

**Comment by Eldinnie** [comment]
done

**Comment by jh0ker** [comment]
Excellent!

**Pull request merged**
