### PR TITLE
Add `last` kwarg to `run_repeating`

### LINKED ISSUE #1333: `last` kwarg for `JobQueue.run_repeating` method
Just as `JobQueue.run_repeating` takes a `first` optional keyword argument, that specifies the first time a job should be run (as a `datetime.datetime` object, for example), I believe it would be convenient to add a `last` optional keyword argument that specified, if relevant, the last time a job should be run.

## Use cases

I can think of a few use cases, but I'm sure there are more. For example, suppose the bot is part of a game, during which it has to send regular updates (by using a `Job`). Suppose the game lasts a fixed amount of time, which set prior to its start; say, 1 hour. Then, by specifying the `last` keyword argument, the bot programmer could set the "regular updates job" to end when the game ends.

## Current alternative

A workaround I have been using is to specify a separate `run_once` job that will run the `schedule_removal` method on the job at the desired time. A better way is to check inside the job's callback, and remove the job from there using `job.schedule_removal()`.

In either case, I find these solutions to be, if not cumbersome, inelegant, compared to having a much simpler-to-use and elegant dedicated feature.

------

A proposed implementation can be found in #1345.

### PR DESCRIPTION
**Pull request by plammens**
Added a `last` keyword argument to the `run_repeating` method of job queues that takes in a time specifier (in the same formats supported by `first`). It specifies the last time the job should be run. Currently, checking if the job should be run or not involves a certain "delay buffer" (so that if `last` is an exact multiple of `interval`, the internal delays don't mess up the intended behaviour), but it's a temporary solution. Also, I've made some minor refactorings.

Tests run correctly from my side. I've added one test for the new feature, but maybe a few more would be in place. The docs haven't been updated yet.

Closes #1333.

### CODE REVIEW

**Comment by Eldinnie** [comment]
Hi,

Thanks for your contribution. As you can see tests fail on py2. This is because you modified the calculation for `_next_t` in a way a `datetime` on py2 will never be accepted.
Can you please fix this?

Pieter

**Comment by plammens** [comment]
Ah! Sorry I missed that. By the way, could time objects be stored as `datetime.datetime` instead of plain timestamps? That would simply it a bit.

**Comment by plammens** [comment]
@Eldinnie Should be fixed now. Though Travis keeps failing on the unrelated `test_idle`.

**Comment by plammens** [comment]
@Eldinnie Any updates on this? I can make changes if the PR is not up to scratch

**Comment by Bibo-Joshi** [comment]
This was closed when the V12 branch was deleted. Would you mind reopening the PR to master, @plammens ? :)

**Comment by plammens** [comment]
@Bibo-Joshi Oh, that makes sense. Reopened as #1497!

**Comment by Bibo-Joshi** [comment]
@plammens Thanks!

**Pull request closed without merging**
