### PR TITLE
Fix and enhance PicklePersistence: deepcopy

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
As reported in [#1297](https://github.com/python-telegram-bot/python-telegram-bot/issues/1297), the use of shallow copies in `PicklePersistence` leads to data not being persisted. Same holds for `DictPersistence` A fix would be the use of `copy.deepcopy`, which however may become time consuming for large data sets.

I therefore implemented an additional argument `on_update` for `Pickle/DictPersistence` that let's you choose wether to check for updates before dumping or not.
If `on_update = False`, checking is obmitted and one can skip time consuming deepcopies (i.e. just pass the actual data). If `on_update = True`, deepcopies are used.

### CODE REVIEW

**Comment by Bibo-Joshi** [comment]
This PR might be redundant (see [#1297](https://github.com/python-telegram-bot/python-telegram-bot/issues/1297#issuecomment-452033841) and [#1322](https://github.com/python-telegram-bot/python-telegram-bot/pull/1322#issue-242742755)).
Leaving this open until #1297 is resolved.

**Comment by jsmnbom** [comment]
I would like to merge this for the V12 beta that I'm working on.
But I'm gonna hold of for now because of the following (please correct me if I'm wrong :))
- Tests are updated but don't actually include a regression test for #1297.
- I still don't 100% understand why we need to copy the data at all?
- And I'm not really sure if on_update is a descriptive enough name for the parameter if we do need it.
- It also feels the parameter should be on BasePersistence and not only subclasses of it?

**Comment by jsmnbom** [comment]
Oh and feel free to reach out to me on telegram @jsmnbom if you wanna help convince and fix these things together so we can get it v12 beta ready :)

**Comment by jsmnbom** [comment]
Superseeded by #1342. We choose to go a simpler route and always deepcopy the data. Thanks a lot for both finding the issue and taking the time to make the PR :D

**Pull request closed without merging**
