### PR TITLE
fix setting default mimetype of inputfile

### PR DESCRIPTION
**Pull request by azogue**
## Description

When **sending a photo as a bytesio stream** and the mimetype isn't detected with the stream header, don't try to guess the type with `self.filename` if filename is `None`. In that case, set the default `application/octet-stream` mimetype.

This fixes this [problem](https://github.com/home-assistant/home-assistant/issues/7413#issuecomment-304508296), because `imghdr.what()` fails when analysing the pic in discuss (https://cloud.githubusercontent.com/assets/6839756/26528267/0df8c88e-43a8-11e7-9e7a-d3820533e437.jpg), so it's related to #589, closed today by @tsnoam.

### CODE REVIEW

**Comment by tsnoam** [comment]
@azogue 
Would you be so kind and add a unitest for that scenario?

**Comment by azogue** [comment]
Testing the pic in discuss and comparing the resulting mimetype? in `test_photo.py`? Do I include the pic with the non standard header in `tests/data/`?

**Comment by tsnoam** [comment]
@azogue Exactly like you decribed, and also try to actually send the photo.
Thank you.

**Comment by jh0ker** [comment]
Thanks :) Travis fails only because of video notes, and the change looks good. Would you like to add yourself to https://github.com/python-telegram-bot/python-telegram-bot/blob/master/AUTHORS.rst before I merge?

**Comment by tsnoam** [comment]
@azogue Thanks for your contribution. Merging now.

**Pull request merged**
