### PR TITLE
edited_updates also for channel_posts

### PR DESCRIPTION
**Pull request by Eldinnie**
including tests

### CODE REVIEW

**Comment by bomjacob** [comment]
To me it would be unintuitive to suddenly receive `edited_channel_posts` in my `MessageHandler(..., allow_edited=False)` without having `channel_post_updates=True` too, but that might just be me?

**Comment by Eldinnie** [comment]
@bomjacob hmm, that's also True. What do you suggest? Although allow_edited is being deprecated. Do you feel the same for edited_updates?

**Comment by bomjacob** [comment]
Yeah sorry that's what I meant. But looking at it now, that might turn out to me unintuitive behaviour since currently `edited_updates` doesn't require `message_updates` to be true for a `edited_message` to be allowed through. So I don't really know... This is just yet another reason for considering refractoring the filter system to handle these things.

**Comment by Eldinnie** [comment]
@bomjacob that is definitely True. But for now I see no way to fix it (without breaking backwards compatibility) other then introducing edited_channel_post_updates as a marker.

**Comment by bomjacob** [comment]
Hmm, that would be okay if `edited_updates` was called `edit_message_updates` but it's not... So I think for now that the change you've made already in the PR might be the best we can do while maintaining backwards compat and not confusing users too much.

**Pull request merged**
