### PR TITLE
rename methods to snake_case

### LINKED ISSUE #255: PEP8 issue: Methods should be snake case
All methods violate the PEP8. I propose to implement both methods and add a DeprecationWarning.

Thanks!

### PR DESCRIPTION
**Pull request by rahiel**
This should solve #259 while keeping backward compatibility for users who don't like to change their existing code. This also fixes #255

### CODE REVIEW

**Comment by tsnoam** [comment]
@rahiel imo, this should issue deprecation warning at first and at a later release remove the backward compatibility

**Comment by rahiel** [comment]
> @rahiel imo, this should issue deprecation warning at first and at a later release remove the backward compatibility

Done! I might have missed some internal invocations the old methods.

Did I miss any other methods?

**Comment by jh0ker** [comment]
Updating examples should be done on release of this, yes?

**Comment by rahiel** [comment]
> Updating examples should be done on release of this, yes?

Yes, I think we should quickly make a new release with the new interface so new users don't have to adapt later.

**Comment by tsnoam** [comment]
@rahiel I think it must come out together with the fixes in my PR from yesterday. I dearly hope to have the time to fix the merge tonight.

**Comment by leandrotoledo** [comment]
Reloading PyPy tests.

**Comment by leandrotoledo** [comment]
Should we get this merged?

**Comment by jh0ker** [comment]
@leandrotoledo LGTM

**Pull request merged**
