### PR TITLE
Fixed typos in the comments of example files

### PR DESCRIPTION
**Pull request by Tr-Jono**

### CODE REVIEW

**Comment by Poolitzer** [comment]
We apparently cant type at all, thanks so much :)

**Comment by Poolitzer** [comment]
Only "problem" I have with your PR is that you neither give your branch an appropriate name, nor add yourself to the author file, but I think we can ignore this. If you'd like to do the appropriate changes, feel free to though :)

**Comment by Tr-Jono** [comment]
idk how to fix the branch thing lol
Would have to open a new PR?

**Comment by Poolitzer** [comment]
yep, you'd have to

**Comment by Tr-Jono** [comment]
See #1537 
Also, I am already in authors

**Comment by Poolitzer** [comment]
hm, my bad then.

**Pull request closed without merging**
