### PR TITLE
Fix readme: Installation with extra [ujson] should be [json].

### PR DESCRIPTION
**Pull request by Behoston**
Just a readme fix.

```
WARNING: python-telegram-bot 13.7 does not provide the extra 'ujson'
```

https://github.com/python-telegram-bot/python-telegram-bot/blob/master/setup.py#L85

### CODE REVIEW

**Comment by harshil21** [comment]
Thanks for the spot, I think it makes more sense to change it to `ujson` in the `setup.py`

**Comment by Behoston** [comment]
agree, `[ujson]` is much clearer, but you need to extend existing setup to support both to backward compatibility. I'm not sure if extend will be ok, so I just fix readme to match code.

**Comment by Bibo-Joshi** [comment]
that's good thinking @Behoston ! however, we're by now working towards v14, which will break a lot of things anyway. So that wouldn't necessarily be a no-go. Anyway, while I somewhat like the idea to rename `json` to `ujson`, the former makes it easier for us to switch to another json-library if we see fit at some point. The other optional requirements `socks` and `passport` are also more a description of what the requirements are for, not which lib would be installed.  So I think I'm slightly more in favor of adjusting the readme as you currently did.

**Comment by Bibo-Joshi** [comment]
Thanks for the contribution!

**Pull request merged**
