### PR TITLE
Turn on branch coverage

### PR DESCRIPTION
**Pull request by bomjacob**
Just testing for now

### CODE REVIEW

**Comment by Eldinnie** [comment]
@bomjacob regarding this, It seems to be working now?

**Comment by bomjacob** [comment]
Sometimes yeah... but imo sometimes isn't good enough

**Comment by Eldinnie** [comment]
I let travis build 5 times and it completed all successful, I would think that;s good enough?

**Comment by bomjacob** [comment]
I mean we can try?
The fact of the matter is that it's failed before though and I have no idea if these changes actually changed anything

**Comment by Eldinnie** [comment]
@bomjacob Having to rerun a build once in a while has happened before with other tests. It runs pretty stable now, I think this could be merged

**Pull request merged**
