### PR TITLE
Attaching thumb file while editing message media.

### PR DESCRIPTION
**Pull request by paradox70**
PTB doesn't attach thumb file while editing media.
I tested the changes manually and it works, but I'm not sure about writing tests in true way.

### CODE REVIEW

**Comment by harshil21** [comment]
hey, have you read the [contributing guidelines](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst)? The tests will keep failing here otherwise.

**Comment by paradox70** [comment]
> hey, have you read the [contributing guidelines](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst)? The tests will keep failing here otherwise.

No, that is a lot works to do in guideline!
I'll check and try it again.

**Comment by Poolitzer** [comment]
shout once you done that (or gave up and I will try to guide you in the correct direction), and I shall review the code :D

**Comment by paradox70** [comment]
Ok, @Poolitzer
I gave up, guide me or do it yourself.

**Comment by Poolitzer** [comment]
> I gave up, guide me

Okay, great. I will have time to do this next week.

**Review by Poolitzer — APPROVED** [review]
Looks good to me! Thanks for the effort and persistence.

**Comment by paradox70** [comment]
Thank you @Poolitzer, I could not do it without your help, you are the best ;D

**Comment by Bibo-Joshi** [comment]
Just one question @Poolitzer : Why did you rebase to v14? I would see this as bug fix and merge this into master …

**Comment by Bibo-Joshi** [comment]
Thanks for the contribution @paradox70 !

**Pull request merged**
