### PR TITLE
Add walrus operator wherever possible

### PR DESCRIPTION
**Pull request by thefunkycat**
Solves #3734 

I have tried to add the walrus operator wherever possible.

I went through most files.
There were a couple more instances I found where I could have added it, but it was unnecessary and would not have necessarily improved readability or code quality.

I was more lenient when it came to adding the walrus operator to tests

### CODE REVIEW

**Comment by thefunkycat** [comment]
@Bibo-Joshi @clot27 is there a reason the `test_send_animation_url_file()` and `test_send_all_args()` are failing? is this me? or is this a pre existing issue

**Comment by Bibo-Joshi** [comment]
Thanks for the PR! The tests are failing on some other PRs since yesterday, too. Seems like something changed in the TG servers. We'll have to investigate.

**Review by Bibo-Joshi — COMMENTED** [review]
The failing tests seem to have recovered. Now only `TestInlineQueryHandler.test_context_pattern` is failing. I guess that's due to your changes though TBH I don't really see a flaw in those … Would you mind double check ing that?

**Comment by thefunkycat** [comment]
@Bibo-Joshi should be fixed now :)

**Comment by Bibo-Joshi** [comment]
Thank you very much for the nice contribution :)

**Pull request merged**
