### PR TITLE
Add filters to commandHandler

### PR DESCRIPTION
**Pull request by jossalgon**
Add filters to CommandHandler.

Now you can filter commands, for example to separate a command from group and private or any filter you want.

```python
updater = Updater(token=TG_TOKEN)
dp = updater.dispatcher

dp.add_handler(CommandHandler('start', start, filter_example))
```

 where filter_example is:
```python
def filter_example(msg):
    return msg.chat.type == 'private'
```

or
```python
updater = Updater(token=TG_TOKEN)
dp = updater.dispatcher

dp.add_handler(CommandHandler('start', start, lambda msg: msg.chat.type == 'private'))
```

### CODE REVIEW

**Comment by Eldinnie** [comment]
I'm looking forward to this, but I think you will have to write some tests for this to get it pulled.

**Comment by jossalgon** [comment]
Do you mean a test on test_updater.py? like:
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/tests/test_updater.py#L169-L185

I didn't find any more tests of commandHandler, thanks for the feedback.

**Comment by jh0ker** [comment]
@jossalgon Yes, indeed. Just add one test case where the filter allows the message and one test case where it doesn't, then we're good to merge I think :+1:

**Comment by jossalgon** [comment]
Are the tests ok in this way?

**Comment by jh0ker** [comment]
Great, but the name of the two test functions says `MessageHandler`, not `CommandHandler` ^^

**Comment by jossalgon** [comment]
:+1: sorry, the commit is now amended

**Comment by jh0ker** [comment]
I'll let the tests run through on Travis before merging, but it looks good. Thank you very much for your contribution :) Did you already add yourself to `AUTHORS.rst`?

**Comment by jossalgon** [comment]
Not yet, I'll add a commit with that and it's a pleasure to collaborate :)

**Comment by Eldinnie** [comment]
Wi=ould you mind adding me to authors to? I forgot and to make a single PR just for that :D
Pieter Schutz github.com/eldinnie

**Comment by jh0ker** [comment]
@Eldinnie I can just commit that directly to master, no need to piggyback it here @jossalgon ^^

**Comment by jh0ker** [comment]
anyways, tests look good so I'll merge now!

**Pull request merged**
