### PR TITLE
Add a prefix to worker thread

### LINKED ISSUE #1332: give threads a name prefix
Just an idea if **_python-telegram-bot_** is part of a bigger program: 

It would be a nice thing to improve bug finding in bigger programms of which python-telegram-bot is a part of if one could name the thread. Instead of names like

```
dispatcher
updater
84a23bc3-ec23-4aeb-be53-f24e7af82544_0
84a23bc3-ec23-4aeb-be53-f24e7af82544_1
84a23bc3-ec23-4aeb-be53-f24e7af82544_2
84a23bc3-ec23-4aeb-be53-f24e7af82544_3
```

I would rather like to see
```
telegram_dispatcher
telegram_updater
telegram_worker_0
telegram_worker_1
telegram_worker_2
telegram_worker_3
```
Since any thread has an id anyway, this should not be too difficult.
So instead using uuid4 to name a worker, just give a custom param of ``name_prefix='telegram'`` and ``worker_name='worker'``

Thanks in advance!

### PR DESCRIPTION
**Pull request by Eldinnie**
This adds a prefix of `Bot:<id>:worker:` to the name of the worker threads.
Fixes #1332

### CODE REVIEW

**Comment by Eldinnie** [comment]
@jsmnbom I will address your notes later, want to see if this indeed fixes Travis' behavior

**Comment by bmxp** [comment]
I am looking forward for your improvements and will try out asap ...

**Comment by jsmnbom** [comment]
@Eldinnie any updates on this? Do you agree with my comments? I can implement them if you dont' have time ^ ^

**Comment by Hukutoss** [comment]
Any updates about this PR? I have the same issue as #1332 ( ._.)

**Comment by bmxp** [comment]
As long as this PR is not accepted into Release 12 I have tricked around with something like this which is not beautiful but does the necessary change:

```
pretty_thread_names = True
prefix_programname = "YourProgramnameHere"
prefix_worker_thread = "Worker"

# theUpdater contains the telegram Updater Object

if pretty_thread_names:
    try:
        for t in theUpdater._Updater__threads:
          if 'dispatcher' in t.name: 
            t.name = prefix_programname+' Dispatcher'
            
          if 'updater' in t.name: 
            t.name = prefix_programname+' Updater'
            
        for t in theUpdater.dispatcher._Dispatcher__async_threads:
          *_, num = t.name.split('_')
          t.name = '{0} {1} {2}'.format(prefix_programname, prefix_worker_thread, num) if num.isnumeric() else num

    except:
        pass
```

**Comment by Eldinnie** [comment]
Renamed all threads and changed base.

**Comment by Eldinnie** [comment]
@jsmnbom care to take another look?

**Comment by jsmnbom** [comment]
This mostly looks good now, but i still don't think i can see my comment 3 adressed?

> 3. I'm not really a fan of having a method just for testing purposes. Can't you just do dp._Dispatcher__async_threads in the test?

**Comment by Eldinnie** [comment]
No you can't.
It's a protected variable

**Pull request merged**
