### PR TITLE
Convenience full_name method for User

### PR DESCRIPTION
**Pull request by graynk**
Returns full name (first + last) if last name is present or just the first name if not present.

### CODE REVIEW

**Comment by robert-cody** [comment]
In many locales format should be "surname name" (which is BTW more useful for sorting), so it's better to make locale as incoming optional parameter and return full_name depending on locale.

**Comment by graynk** [comment]
I don't think this information is in python [locale](https://docs.python.org/3/library/locale.html) module though? 
It seems to have been in CLDR at [some](https://unicode.org/cldr/trac/ticket/177) point, but not anymore, if I understand it correctly. In any case, I view this as just a simpler version of User.name method that works exactly the same way, only ensuring that returned names are consistent in style (I feel that mentioning some users via "@username" and others via "name" is unintuitive and doesn't look all that well in group chats).

**Comment by robert-cody** [comment]
@graynk you're right, for some strange reason, there is no such info in Python's locale module.

**Comment by Eldinnie** [comment]
Looks good to me. Closes #943

**Comment by tsnoam** [comment]
thank you for your contribution

**Pull request merged**
