### PR TITLE
File.downbyte added

### PR DESCRIPTION
**Pull request by OctoNezd**
Please notice:I haven`t changed File.download() behaviour, because it will ruin backwards compability.

### CODE REVIEW

**Comment by bomjacob** [comment]
Please explain how making `file.download()` also accept file like objects and changing behaviour depending on it in any way breaks backwards compatibility.

**Comment by OctoNezd** [comment]
Because I think many of bots use code like this:
`File.download(id, "blah-blah-blah")`
And when suddendly, args change to id, file, cpath, their code will break. Am I right?/

**Comment by bomjacob** [comment]
Not really no.
Since python is not a statically typed language, a method can accept a parameter that could be different types. Then inside the function you check (using `isinstance`) the type of the parameter and act accordingly.

**Comment by OctoNezd** [comment]
https://travis-ci.org/python-telegram-bot/python-telegram-bot/jobs/173651523
Line 983: I think its not mine code fault

**Comment by OctoNezd** [comment]
Oh. I will update code and make new pull req
P.S. I hope I haven`t annoyed you with mine PR`s

**Comment by bomjacob** [comment]
There's really no need to make a separate PR every time something needs to be changed, but alright :)

**Pull request closed without merging**
