### PR TITLE
Fixed message decorator to use default arguments of wrapped functions

### PR DESCRIPTION
**Pull request by jonbesga**

### CODE REVIEW

**Comment by Eldinnie** [comment]
Hi,

I'm not sure I understand the problem in the issue you made, but as far as I understand you're thinking that if you pass: `bot.send_audio(chat_id, audio, timeout=20)`. The timeout will be ignored by the bot class because of the message decorator right?

This concern is unwarrented though.
If you look at this line in de `@message` decorator in the bot class:
https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L85
You see it take's the timeout from the kwargs.

**Comment by jonbesga** [comment]
Hi,

The concern is that if you don't pass the argument timeout to `bot._send_audio`. There is no default timeout.

**Comment by Eldinnie** [comment]
Well as you can see on this line. `send_audio` (I think you meant that) has a defauklt timeout of 20

https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/bot.py#L396

**Comment by jonbesga** [comment]
Exactly. And that value is not passed to the decorator.

**Comment by jsmnbom** [comment]
You would indeed be correct in that default timeout are not getting applied at all. And I gotta give you probs for taking the initiative to write a pr.
However, I'm not a fan of how this has been fixed - using the inspect module makes code much harder to read and comprehend (and correct me if I'm wrong, but its performance is pretty bad too, right?).
Therefore I think a better fix is gonna be to get rid of the message decorator, and instead turn it into a method and call it explicitly at the bottom of send_* etc.
@jonbesga Would you like to write this fix, or should we quickly fix it ourselves? :)

(@tsnoam is totally gonna have a field day with this xD)

**Comment by jsmnbom** [comment]
We'll also need a test to make sure something like this doesn't happen again in the future. I adapted one quickly:
``` python
    def test_timeout_propagation_implicit(self, monkeypatch, bot, chat_id):
        class OkException(Exception):
            pass

        def post(*args, **kwargs):
            print(kwargs)
            if kwargs.get('timeout') == 20:
                raise OkException

        monkeypatch.setattr('telegram.utils.request.Request.post', post)

        with pytest.raises(OkException):
            bot.send_photo(chat_id, open('tests/data/telegram.jpg', 'rb'))
```

**Comment by jsmnbom** [comment]
Alright I will close this PR then and add some info to #1145.

**Pull request closed without merging**
