### PR TITLE
Conversation

### PR DESCRIPTION
**Pull request by njittam**
Hey,
I added support for what I call conversations.
This is like when you create a new bot the botfather ask you first for a name and then for a for a username.
I also added an example.
In this example the bot will wait for a /start.
the will ask the user to enter some words.
When the user enters a '.' bot wil say the sentance and the conversation will be ended.

### CODE REVIEW

**Comment by naveenvhegde** [comment]
Hi,

Saw your implementation. Can you explain more about how to handle conversation. 

How to handle states with in conversation ?

**Comment by njittam** [comment]
Hi, 
Well the dispatcher will initiate one object for one chat. So when in chat 1 someone says /start and in chat 2 someone else says /start in the example. There will be two objects initiated. One for every Chat. 
This way you can keep track of states within your class.

The only two states the dispatcher cares about is 'running' and 'not running'.
to say to the dispatcher hey I am not done yet you let the __call__ method return False
and when the conversation is over you return True.

**Comment by tsnoam** [comment]
Hi @njittam 

It seems like there were CI failures on the code. Have you checked it prior to push?

Anyway, the idea of a "Conversation" bot seems like a very good idea to us & we would be happy to add it. However, we were wondering whether it really requires an infrastructural change and can't be implemented using the current dispatching mechanism?
Do you think the "Conversation" bot can be modified to be implemented as an example (and added to the `examples` dir)?

 - Noam

**Comment by njittam** [comment]
Hi, 
I am going to close this pull request because it failed the tests.
It might not be necessary to but in my opinion is this a really easy way to implement a conversation to your bot.
I already created an example.

**Comment by naveenvhegde** [comment]
@njittam, having conversation integrated with library is great, but it requires a lot of thoughts as it has state associated with it.

I suggest you write up a wiki on the project page about your thoughts and once the idea gets concrete, it will be easy to implement.

**Comment by njittam** [comment]
will do.

**Comment by jh0ker** [comment]
@njittam Please check out our latest 4.0rc1 release. Your proposal should integrate very nicely with it, due to structural changes in the Dispatcher.

**Pull request closed without merging**
