### PR TITLE
user text mention for html and markdown parse

### PR DESCRIPTION
**Pull request by ehsanonline**

### CODE REVIEW

**Comment by jsmnbom** [comment]
Thanks a lot for the PR @ehsanonline, it seems to look really great :D
Could we perhaps get you to write a test case for the new behaviour?

**Comment by Eldinnie** [comment]
Great addition! We overlooked this.
In addition to what @jsmnbom asked, please take a look at our [Contribution guide](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/.github/CONTRIBUTING.rst). It outlines how to install the pre-commit hook so the flake8 error's don;t commit.

**Comment by ehsanonline** [comment]
I followed your tutorial but I could not pull my branch with patch-1 branch name (non-fast-forward error), so I made a new branch name and new pull request. sorry about that.

**Comment by Eldinnie** [comment]
Closing this as it's superseeded by #1206

**Pull request closed without merging**
