### PR TITLE
Create Filters.channel

### PR DESCRIPTION
**Pull request by marcroga**
Filters messages sent in a channel chat.

### CODE REVIEW

**Comment by jusim333** [comment]
good

**Comment by jsmnbom** [comment]
As with #1104 I'm gonna close this. The reason is that it's implemented as part of #1221. Thanks for taking the time to submit a PR though, we always appreciate it :D

**Comment by jsmnbom** [comment]
Actually scratch that, #1221 has the update.channel_post, but this filter would also detect forwarded channel messages so we might actually want both. Reopening and we'll check it out :)

**Comment by Eldinnie** [comment]
I don;t think `message.chat.type == 'channel'` on forwarded channel messages....

**Comment by jsmnbom** [comment]
@Eldinnie You're indeed right. If you need that info you'd need to check `forwarded_from_chat.type`. And I feel like having filters for those is too specific.
Closing since #1221 includes update.channel which does pretty much the same :)

Once again thanks for taking the time to submit a PR though, we always appreciate it :D

**Pull request closed without merging**
