### PR TITLE
Fix Docs Search in Sphinx 6.0+

### PR DESCRIPTION
**Pull request by harshil21**
Fixes doc search in sphinx 6.0+. (~This is not fixed at readthedocs-sphinx-search yet~ Was fixed and merged into my fork)

Build at: https://docs.python-telegram-bot.org/en/doc-improve-search

Changelog at: https://github.com/harshil21/furo-sphinx-search/commits/main (see commit msgs)

Todo now that I started this again:
- [ ] ~Sort search results such that highlighted results on the left are prioritized over ones only on the right~
- [ ] ~Experimental: Prefix search if only one word has been typed, so we get better results.~

### CODE REVIEW

**Comment by harshil21** [comment]
Auto modification of search query seems to be futile.. and since API v3, most search results seem to be sorted anyway, so that is not worth the effort.

PR can be merged/reviewed now

**Comment by Bibo-Joshi** [comment]
Thanks for the PR!

> Auto modification of search query seems to be futile.

Can you remind me what "auto modification of search query" means? 😬 

> This is not fixed at readthedocs-sphinx-search yet

IMO it's worth a try to PR against upstream with these changes first. If they adopt the proposed changes, you can merge into your branch. This reduces the risk of merge conflicts. However, I don't know if your branch has already diverged too much from upstream, i.e. if your changes are not applicable to upstream anymore, that's ofc a different story.

**Comment by harshil21** [comment]
> Can you remind me what "auto modification of search query" means? 😬

I mean [this](https://docs.readthedocs.io/en/stable/server-side-search/syntax.html#special-queries). I hoped that doing something like `send_mes*` (the * is added to the query automatically) give send_message as a search result, but it does not and instead it makes it worse in some cases, e.g. `send_message*` does not give you Bot.send_message as a result (I would expect it to). Their backend for search is very poor imo.

> IMO it's worth a try to PR against upstream with these changes first. 

I did open an issue yesterday (https://github.com/readthedocs/readthedocs-sphinx-search/issues/126), no response yet

**Comment by Bibo-Joshi** [comment]
> Their backend for search is very poor imo.

They = Sphinx?

I saw the issue, but I didn't see a PR yet

**Comment by Bibo-Joshi** [comment]
https://github.com/readthedocs/readthedocs-sphinx-search/issues/126 has been resolved by now. Can you update your branch accordingly?

**Comment by harshil21** [comment]
> [readthedocs/readthedocs-sphinx-search#126](https://github.com/readthedocs/readthedocs-sphinx-search/issues/126) has been resolved by now. Can you update your branch accordingly?

yeah will do tomorrow or day after

**Pull request merged**
