### PR TITLE
Refactor and overhaul `test_official`

### LINKED ISSUE #3874: Refactor `test_official` to be more modular
`test_offcial` has evolved greatly over time with #3868 introducing yet more extensive testing.
To keep order in there, we should try to get it a bit more moduler. Ideas:

* move helper functions to a different module
* move configurations about PTB exceptions to a different module
* make checking of existence, optional arguments, type hints different module
* Maybe class-based approaches (e.g. wrapping python objects and corresponding documentation into one container) may make sense

### PR DESCRIPTION
**Pull request by harshil21**
Closes #3874 

Features of the overhauled `test_official`:

- Modularized
- Scraping is now done in the beginning and is conveniently wrapped in python classes, and is frozen since it represents the ground truth.
- Logging: some logging statements are used in the `check_param_type` function. If you run pytest with `--log-level=DEBUG` and that test fails, you'll see the logged statements.
- Major simplification for `check_param_type` function. See https://github.com/python-telegram-bot/python-telegram-bot/pull/4087#issuecomment-1926675636 and https://github.com/python-telegram-bot/python-telegram-bot/pull/4087/commits/f5704da25d3b998ea2a1e44cacad064480d03c0e 's commit message.
- Some simplification in other places and more documentation

If you see any more areas of improvement, feel free to mention it.

### CODE REVIEW

**Comment by Bibo-Joshi** [comment]
I scrolled through the changes and didn't see anything that made me want to leave a comment. IISC much of the changes are reorderings, additional comments & extraction of methods, so I've seen most of the code before as well. - Which is ofc not meant to downplay the work you've put into this PR and the gain in maintenability this brings!

You added the do-not-merge label. Do you want to merge after API 7.0?

**Comment by harshil21** [comment]
> I scrolled through the changes and didn't see anything that made me want to leave a comment. IISC much of the changes are reorderings, additional comments & extraction of methods, so I've seen most of the code before as well. - Which is ofc not meant to downplay the work you've put into this PR and the gain in maintenability this brings!

yeah there are just tiny changes here and there to make it easier to maintain, but the code is largely the same.

> You added the do-not-merge label. Do you want to merge after API 7.0?

Yes, and that would also give me time to see if I can simplify / improve the `check_param_type` function..

**Comment by harshil21** [comment]
Latest commits significantly improve `check_param_type` function, reducing lines of code for that function by **66.4%** (excluding newly added logging code)

As a result of simplification, it also found incorrect type hints which went undetected before. There was also further "modularization" making the code easier to follow.

To be merged after #4089 and #4034.

**Comment by Bibo-Joshi** [comment]
Sorry again for the merge mess-up and big kudos for the PR!

**Pull request merged**
