### PR TITLE
Added myself to Authors list

### PR DESCRIPTION
**Pull request by ihoru**
Due to this #738 

P.S. I didn't do anything with `urllib3/util/connection.py`, just merged it from upstream... I don't understand, why is it so. If you can recommend anything how to solve this problem, I would be very glad!

### CODE REVIEW

**Comment by tsnoam** [comment]
@ihoru 
there was a change in the git submodules.
you need to do:
```git submodule update --init --recursive``
but you first have to revert your changes.

**Comment by ihoru** [comment]
@tsnoam thank you for your help!
We need to add a note about this to contribution file...

**Comment by tsnoam** [comment]
@ihoru It's in the README but improvements are always welcome.

**Comment by ihoru** [comment]
@tsnoam done #763

**Pull request merged**
