### PR TITLE
Fix Server response could not be decoded using UTF-8

### PR DESCRIPTION
**Pull request by rikonaka**
- Remove the handling of `UnicodeDecodeError` errors beacause of using the `decoded_s = json_data.decode('utf-8', 'replace')`.

- Remove test for invalid JSON data cause there is no more error caused by decoding utf-8..

issues [#1609](https://github.com/python-telegram-bot/python-telegram-bot/issues/1609)

### CODE REVIEW

**Comment by rikonaka** [comment]
I have some doubts about this automated test result.
```
test_send_live_location failed (2 runs remaining out of 3).
	<class 'telegram.error.BadRequest'>
	Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
	[<TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/tests/test_location.py:60>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:66>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:1160>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:123>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/utils/request.py:323>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/utils/request.py:234>]
test_send_live_location failed (1 runs remaining out of 3).
	<class 'telegram.error.BadRequest'>
	Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
	[<TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/tests/test_location.py:60>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:66>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:1160>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/bot.py:123>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/utils/request.py:323>, <TracebackEntry /home/runner/work/python-telegram-bot/python-telegram-bot/telegram/utils/request.py:234>]
```
I have never modified the code for `test_location.py`.

This should be solved by the guy responsible for this module.

**Comment by Bibo-Joshi** [comment]
The main problem still is `test_parse_illegal_callback_data`, since now no error is raised. Please adjust it accordingly.

**Comment by rikonaka** [comment]
> The main problem still is `test_parse_illegal_callback_data`, since now no error is raised. Please adjust it accordingly.
I think may be we should drop the invaild data which use `ignore` instead of `replace`.

**Comment by Bibo-Joshi** [comment]
`test_parse_illegal_callback_data` is still expecting an error, though ;)

**Comment by rikonaka** [comment]
> `test_parse_illegal_callback_data` is still expecting an error, though ;)

Yes, I know where is the problem now, I use the `replace` or `ignore` in decode function, so there is no TelegramError anymore, I will remove this test for invalid data.

**Comment by rikonaka** [comment]
I think it should be okay now.

**Comment by isjerryxiao** [comment]
Maybe my solution #1651 is better.

**Comment by rikonaka** [comment]
> Maybe my solution #1651 is better.

I have read your code and comment in your pull request, and it didn't solve any problem...😂

**Comment by isjerryxiao** [comment]
It definitely solves the problem.

**Comment by tsnoam** [comment]
failure in unitests is unrelated

**Comment by tsnoam** [comment]
@rikonaka thank you for your contribution

**Pull request merged**
