### PR TITLE
Make chat_id a positional argument inside shortcut methods of Chat and User classes #1048

### PR DESCRIPTION
**Pull request by xates**

### CODE REVIEW

**Comment by jh0ker** [comment]
@xates Looks like you also have to update the tests

**Comment by xates** [comment]
Ok, I have tried to figure out how they work but I am not entirely sure... would something like that work?

```python

    def test_instance_method_send_message(self, monkeypatch, chat):
        def test(*args, **kwargs):
            return args[0] == chat.id and args[1] == 'test'

        monkeypatch.setattr('telegram.Bot.send_message', test)
        assert chat.send_message('test')

    def test_instance_method_send_audio(self, monkeypatch, chat):
        def test(*args, **kwargs):
            return args[0] == chat.id and args[1] == 'test_audio'

        monkeypatch.setattr('telegram.Bot.send_audio', test)
        assert chat.send_audio('test_audio')
```

Moreover, I have noticed that both Chat and the User class lack the tests for `send_picture`. Is that intentional or should I add them?

**Comment by jh0ker** [comment]
I believe that will work, but please confirm it locally before committing (as per contributing guide). 

And yes, that looks like an oversight, adding tests for `send_photo` would be appreciated :+1:

**Comment by xates** [comment]
I cannot run the tests locally because I get an ImportError: No module named ptb_urllib3.urllib3

**Comment by Eldinnie** [comment]
@xates Looks like you didn't follow this step from the contributing guide:
```
Clone your forked repository of python-telegram-bot to your computer:

$ git clone https://github.com/<your username>/python-telegram-bot --recursive
```
To fix it run:
```
$ git submodule update --init --recursive

**Comment by jh0ker** [comment]
@xates Sounds like you didn't clone with `--recursive` to also clone git submodules (as per contribution guide)

**Comment by xates** [comment]
You're right, sorry, I missed that `--recursive` that was at the end

**Comment by jh0ker** [comment]
If you get errors in `test_get_chat` you can ignore them

**Comment by xates** [comment]
Oh, I see! That was driving me crazy...

**Comment by jh0ker** [comment]
I'm sorry about that, someone unwittingly renamed the group that is used in that test so the test suddenly failed everywhere.

**Comment by jh0ker** [comment]
Looks good to me :+1:

**Comment by jh0ker** [comment]
Thank you very much for your contribution :)

**Comment by xates** [comment]
Yeah, I guess that SSL problem is not my fault :smile: 

Well, thank you, for running such a wonderful project :wink:

**Comment by jh0ker** [comment]
Eh, tests sometimes pass and fail depending on the alignment of the planets :new_moon:

**Pull request merged**
