### PR TITLE
Allow persistence with non telegram.Update updates

### PR DESCRIPTION
**Pull request by jsmnbom**
Update types used with TypeHandler, doesn't necessarily have a `effective_chat` and `effective_user`. Therefore we need to make sure that it's an instance of telegram.Update before assuming those attributes exist.

I'm unsure how to test... any suggestions?

### CODE REVIEW

**Comment by jh0ker** [comment]
Looks good. As for testing, run some arbitrary update through a persistence-enabled dispatcher and `assert(True)` after? Or something to that effect.

**Comment by JosXa** [comment]
@jsmnbom Shouldn't we rather go with duck typing and assume that when it looks like an Update and behaves like an Update, it probably is something like an update?
Long story short: if hasattr(obj, 'effective_chat') checks rather than isinstance

**Comment by Eldinnie** [comment]
I think we should add this.

**Comment by Eldinnie** [comment]
@JosXa can you explain why we would do that?

**Comment by JosXa** [comment]
Well if users choose to create their own versions of the `Update` class but do not necessarily inherit from or our built-in one, then the check will fail even though the object has the same signature

**Pull request merged**
