### PR TITLE
Fixed typo in README

### PR DESCRIPTION
**Pull request by seadog007**
### Checklist for PRs

- [ ] Added `.. versionadded:: version`, `.. versionchanged:: version` or `.. deprecated:: version` to the docstrings for user facing changes (for methods/class descriptions, arguments and attributes)
- [ ] Created new or adapted existing unit tests
- [ ] Added myself alphabetically to `AUTHORS.rst` (optional)

### CODE REVIEW

**Comment by Poolitzer** [comment]
Set the logging level, sure. But I think "install from source" is the correct technically term. Why did you put a the there?

**Comment by seadog007** [comment]
My bad, fixing that

**Comment by Bibo-Joshi** [comment]
I'm pretty sure that `setting` is correct here. The sentence basically reads `You can also use logs in your application by [...] stetting the log level you want:` or `You can also use logs in your application by calling ``logging.getLogger()`` and by setting the log level you want:`

**Comment by harshil21** [comment]
@Bibo-Joshi Yeah &#x27;setting&#x27; sounds right

**Comment by Bibo-Joshi** [comment]
I'll go ahead and close, then. Still, thank you @seadog007 for reaching out with improvement suggestions! I've you're interested in other doc improvements, you can have a look at #2633 :)

**Pull request closed without merging**
