### PR TITLE
add docs for bot api 3.0 modules

### PR DESCRIPTION
**Pull request by jeffffc**
however, readthedocs failed to build the docs because of https://github.com/python-telegram-bot/python-telegram-bot/commit/87b096c7f94045101bbe7887c2ce03a9b2e54e8b specifying sphinx of minimum version `1.5.4` while RTD is default at `1.5.3`
i think we have to either:
1. specify `sphinx==1.5.4` at `requirements.txt`, which should not be the case because it is not a must for all users to install sphinx, or:
2. specify it at `docs/requirements-docs.txt` and force RTD to install the dependencies there (need config at RTD)

### CODE REVIEW

**Comment by rahiel** [comment]
Thanks for your contribution! This looks good to merge.

**Comment by bomjacob** [comment]
Please wait for approval by @Eldinnie, since I know he's working on docs stuff :)

**Comment by Eldinnie** [comment]
Looks good but one question. Please remove the :undoc-members:

**Comment by jeffffc** [comment]
@Eldinnie Done, thanks for the review. But what about the sphinx version issue? is it solved?

**Comment by bomjacob** [comment]
@Eldinnie Is this superseeded by #728 ?

**Comment by Eldinnie** [comment]
No, this is seperate, adds the new classes to the toctree. Also one last remark @jeffffc can you add all these files to `docs/source/telegram.rst` in their alphabetical place? Else they won;t show up at all.

@bomjacob In #728 I update the docs in the files. This one adds them to the actual docs build.

**Comment by bomjacob** [comment]
I see. Should we merge them into docs_update instead of master, so we can compile the docs with the new docstrings and see if they are satisfactory?

**Comment by Eldinnie** [comment]
Oops, forgot these are already integrated in #728 . Thanks for your effort!
Closing

**Comment by rahiel** [comment]
I'd still like this to be merged first, then #728.

**Pull request merged**
