### PR TITLE
Added copy button in docs

### PR DESCRIPTION
**Pull request by shivamsn97**
Added copy button on docs using sphinx-copybutton (https://sphinx-copybutton.readthedocs.io/en/latest/)

### CODE REVIEW

**Review by lemontree210 — APPROVED** [review]
LGTM (I tried building the docs locally and it does add the copy button to all code snippets)

**Comment by lemontree210** [comment]
Oh, just one thing. Shouldn't the PR be against `doc-fixes` branch?

**Comment by lemontree210** [comment]
The base branch should be `doc-fixes` for this PR. When I changed the base branch it obviously messed up a lot of things :)

I guess you can rebase or just create a new PR, this time creating your local branch off `doc-fixes`, not `master`,  the apply commit 20e9c30 with `git cherry-pick`.  Whatever is easier.

(Unless my more experienced colleagues correct me :))

**Comment by shivamsn97** [comment]
Okay, I will make a new PR to the doc-fixes branch. Closing this PR for now.

**Pull request closed without merging**
